<%
	SQLPendingSLS = "SELECT " & _
	"DECODE(COUNT(*) OVER (PARTITION BY PRIORITY),1,NULL,'T-') || TO_CHAR(TO_DATE(PRIORITY,'J'),'fmjth') PRIORITY, " & _
	"CD_START, " & _
	"CD_END, " & _
	"USE_AGENT, " & _
	"AGENT_NAME, " & _
	"SUPERVISOR_NAME, " & _
	"USE_WORKGROUP, " & _
	"USE_CLASS, " & _
	"USE_LOCATION, " & _
	"NOTE_BOOL, " & _
	"WAIVER_BOOL, " & _
	"UNP_REMAINING, " & _
	"AGENT_COUNT " & _
	"FROM " & _
	"( " & _
		"SELECT " & _
		"RANK() OVER (ORDER BY UNPAID_CHECK DESC, EVAL_CHECK DESC, EPI_CHECK DESC, CD_END, CDPT_CHECK DESC) PRIORITY, " & _
		"GREATEST(CD_START,TO_DATE(CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE)) + ROUND(TO_CHAR(CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE),'SSSSS')/360)/240) CD_START, " & _
		"CD_END, " & _
		"AGT.OPS_USR_ID USE_AGENT, " & _
		"AGT.OPS_USR_NAME AGENT_NAME, " & _
		"SUP.OPS_USR_NAME SUPERVISOR_NAME, " & _
		"DECODE(OPS_USD_TEAM,'SLS','Sales Specialty','RES Sales') || " & _
		"CASE " & _
			"WHEN OPS_ASN_OPS_ASM_ID = 43 THEN ' - Dual' " & _
			"WHEN OPS_ASN_OPS_ASM_ID = 5 THEN ' - Intl' " & _
			"WHEN OPS_ASN_OPS_ASM_ID = 4 THEN ' - Haw' " & _
			"WHEN OPS_ASN_OPS_ASM_ID = 3 THEN ' - Car' " & _
		"END USE_WORKGROUP, " & _
		"DECODE(OPS_USD_CLASS,'RGFT','Reg Full-Time','RGPT','Reg Part-time','PT<30','PT Less Than 30','LEAVE','On Leave') USE_CLASS, " & _
		"DECODE(OPS_USD_LOCATION,'MOT','In-House','WFH','Work From Home','WFD','Work From Distance') USE_LOCATION, " & _
		"NVL2(NOTE_USR_ID,1,0) NOTE_BOOL, " & _
		"NVL2(WAIVER_USR_ID,1,0) WAIVER_BOOL, " & _
		"UNP_REMAINING, " & _
		"COUNT(*) OVER () AGENT_COUNT " & _
		"FROM " & _
		"( " & _
			"SELECT " & _
			"CD.OPS_USR_ID, " & _
			"GREATEST(CD_START,SCHEDULE_START) CD_START, " & _
			"LEAST(CD_END,SCHEDULE_END) CD_END, " & _
			"CDPT_CHECK, " & _
			"CASE WHEN 24*(LEAST(CD_END,SCHEDULE_END) - CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE)) < 1 THEN 1 ELSE EVAL_CHECK END EVAL_CHECK, " & _
			"CASE WHEN 24*(LEAST(CD_END,SCHEDULE_END) - CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE)) < 1 THEN 1 ELSE EPI_CHECK END EPI_CHECK, " & _
			"UNPAID_CHECK, " & _
			"UNP_REMAINING, " & _
			"OPS_ASN_OPS_ASM_ID, " & _
			"COUNT(*) OVER (PARTITION BY CD.OPS_USR_ID ORDER BY GREATEST(CD_START,SCHEDULE_START), LEAST(CD_END,SCHEDULE_END)) CD_COUNT " & _
			"FROM " & _
			"( " & _
				"SELECT " & _
				"OPS_USR_ID, " & _
				"LEAST(CONNECT_BY_ROOT(CDPT_CHECK),CDPT_CHECK) CDPT_CHECK, " & _
				"CONNECT_BY_ROOT(OPS_SCI_START) CD_START, " & _
				"OPS_SCI_END CD_END " & _
				"FROM " & _
				"( " & _
					"SELECT " & _
					"OPS_USR_ID, " & _
					"CDPT_CHECK, " & _
					"SCHEDULE_TYPE, " & _
					"OPS_SCI_START, " & _
					"OPS_SCI_END, " & _
					"CASE " & _
					"WHEN SCHEDULE_TYPE = 'LUNCH' THEN 0 " & _
					"WHEN LAG(START_FLAG) OVER (PARTITION BY OPS_USR_ID ORDER BY OPS_SCI_START) = 1 " & _
					"AND LAG(SCHEDULE_TYPE) OVER (PARTITION BY OPS_USR_ID ORDER BY OPS_SCI_START) = 'LUNCH' " & _
					"AND LAG(OPS_SCI_END) OVER (PARTITION BY OPS_USR_ID ORDER BY OPS_SCI_START) = OPS_SCI_START THEN 1 " & _
					"ELSE START_FLAG " & _
					"END START_FLAG " & _
					"FROM " & _
					"( " & _
						"SELECT OPS_USR_ID, " & _
						"CDPT_CHECK, " & _
						"SCHEDULE_TYPE, " & _
						"CONNECT_BY_ROOT(OPS_SCI_START) OPS_SCI_START, " & _
						"OPS_SCI_END, " & _
						"CASE " & _
						"WHEN LEAD(OPS_SCI_END) OVER (PARTITION BY OPS_USR_ID ORDER BY CONNECT_BY_ROOT(OPS_SCI_START)) IS NULL " & _
						"AND SCHEDULE_TYPE = 'LUNCH' THEN -1 " & _
						"WHEN LEAD(CONNECT_BY_ROOT(OPS_SCI_START)) OVER (PARTITION BY OPS_USR_ID ORDER BY CONNECT_BY_ROOT(OPS_SCI_START)) <> OPS_SCI_END " & _
						"AND SCHEDULE_TYPE = 'LUNCH' THEN -1 " & _
						"WHEN LAG(OPS_SCI_END) OVER (PARTITION BY OPS_USR_ID ORDER BY CONNECT_BY_ROOT(OPS_SCI_START)) IS NULL " & _
						"OR LAG(OPS_SCI_END) OVER (PARTITION BY OPS_USR_ID ORDER BY CONNECT_BY_ROOT(OPS_SCI_START)) <> CONNECT_BY_ROOT(OPS_SCI_START) THEN 1 " & _
						"ELSE 0 " & _
						"END START_FLAG " & _
						"FROM " & _
						"( " & _
							"SELECT OPS_SCI_OPS_USR_ID OPS_USR_ID, " & _
							"DECODE(OPS_SCI_TYPE,'CDPT',1,0) CDPT_CHECK, " & _
							"DECODE(OPS_SCI_TYPE,'LNCH','LUNCH','LNFL','LUNCH','CD') SCHEDULE_TYPE, " & _
							"OPS_SCI_START, " & _
							"OPS_SCI_END, " & _
							"CASE " & _
								"WHEN LAG(OPS_SCI_END) OVER (PARTITION BY OPS_SCI_OPS_USR_ID ORDER BY OPS_SCI_START) IS NULL " & _
								"OR LAG(OPS_SCI_END) OVER (PARTITION BY OPS_SCI_OPS_USR_ID ORDER BY OPS_SCI_START) <> OPS_SCI_START " & _
								"OR LAG(DECODE(OPS_SCI_TYPE,'LNCH','LUNCH','LNFL','LUNCH','CD')) OVER (PARTITION BY OPS_SCI_OPS_USR_ID ORDER BY OPS_SCI_START) <> DECODE(OPS_SCI_TYPE,'LNCH','LUNCH','LNFL','LUNCH','CD') THEN 1 " & _
								"ELSE 0 " & _
							"END START_FLAG " & _
							"FROM OPS_SCHEDULE_INFO " & _
							"WHERE TO_DATE(OPS_SCI_START) = TO_DATE(?,'MM/DD/YYYY') " & _
							"AND " & _
							"( " & _
								"( " & _
									"OPS_SCI_STATUS = 'SUB' " & _
									"AND OPS_SCI_TYPE IN ('CDUN','CDPT') " & _
								") " & _
								"OR " & _
								"( " & _
									"OPS_SCI_STATUS = 'APP' " & _
									"AND OPS_SCI_TYPE IN ('LNCH','LNFL') " & _
								") " & _
							") " & _
							"AND OPS_SCI_START <> OPS_SCI_END " & _
							"AND CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE) < OPS_SCI_END " & _
							"AND OPS_SCI_OPS_USR_ID IN " & _
							"( " & _
								"SELECT DISTINCT OPS_SCI_OPS_USR_ID " & _
								"FROM OPS_SCHEDULE_INFO " & _
								"JOIN RES_ROUTING " & _
								"ON OPS_SCI_OPS_USR_ID = RES_RTE_OPS_USR_ID " & _
								"AND RES_RTE_YEAR = TO_CHAR(CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE)-(6/24),'YYYY') " & _
								"AND RES_RTE_MONTH = TO_CHAR(CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE)-(6/24),'MM') " & _
								"WHERE TO_DATE(OPS_SCI_START) = TO_DATE(?,'MM/DD/YYYY') " & _
								"AND OPS_SCI_STATUS = 'SUB' " & _
								"AND OPS_SCI_OPS_USR_TYPE = 'RES' " & _
								"AND OPS_SCI_TYPE IN ('CDUN','CDPT') " & _
								"AND RES_RTE_RES_RTG_ID IN (1,2,3) " & _
								"AND CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE) < OPS_SCI_END " & _
							") " & _
						") " & _
						"WHERE CONNECT_BY_ISLEAF = 1 " & _
						"START WITH START_FLAG = 1 " & _
						"CONNECT BY OPS_USR_ID = PRIOR OPS_USR_ID " & _
						"AND OPS_SCI_START = PRIOR OPS_SCI_END " & _
						"AND SCHEDULE_TYPE = PRIOR SCHEDULE_TYPE " & _
					") " & _
					"WHERE START_FLAG <> -1 " & _
				") " & _
				"WHERE CONNECT_BY_ISLEAF = 1 " & _
				"START WITH START_FLAG = 1 " & _
				"CONNECT BY OPS_USR_ID = PRIOR OPS_USR_ID " & _
				"AND OPS_SCI_START = PRIOR OPS_SCI_END " & _
			")CD " & _
			"JOIN " & _
			"( " & _
				"SELECT " & _
				"OPS_USR_ID, " & _
				"CONNECT_BY_ROOT(OPS_SCI_START) SCHEDULE_START, " & _
				"OPS_SCI_END SCHEDULE_END " & _
				"FROM " & _
				"( " & _
					"SELECT " & _
					"OPS_USR_ID, " & _
					"SCHEDULE_TYPE, " & _
					"OPS_SCI_START, " & _
					"OPS_SCI_END, " & _
					"CASE " & _
					"WHEN SCHEDULE_TYPE = 'LUNCH' THEN 0 " & _
					"WHEN LAG(START_FLAG) OVER (PARTITION BY OPS_USR_ID ORDER BY OPS_SCI_START) = 1 " & _
					"AND LAG(SCHEDULE_TYPE) OVER (PARTITION BY OPS_USR_ID ORDER BY OPS_SCI_START) = 'LUNCH' " & _
					"AND LAG(OPS_SCI_END) OVER (PARTITION BY OPS_USR_ID ORDER BY OPS_SCI_START) = OPS_SCI_START THEN 1 " & _
					"ELSE START_FLAG " & _
					"END START_FLAG " & _
					"FROM " & _
					"( " & _
						"SELECT OPS_USR_ID, " & _
						"SCHEDULE_TYPE, " & _
						"CONNECT_BY_ROOT(OPS_SCI_START) OPS_SCI_START, " & _
						"OPS_SCI_END, " & _
						"CASE " & _
						"WHEN LEAD(OPS_SCI_END) OVER (PARTITION BY OPS_USR_ID ORDER BY CONNECT_BY_ROOT(OPS_SCI_START)) IS NULL " & _
						"AND SCHEDULE_TYPE = 'LUNCH' THEN -1 " & _
						"WHEN LEAD(CONNECT_BY_ROOT(OPS_SCI_START)) OVER (PARTITION BY OPS_USR_ID ORDER BY CONNECT_BY_ROOT(OPS_SCI_START)) <> OPS_SCI_END " & _
						"AND SCHEDULE_TYPE = 'LUNCH' THEN -1 " & _
						"WHEN LAG(OPS_SCI_END) OVER (PARTITION BY OPS_USR_ID ORDER BY CONNECT_BY_ROOT(OPS_SCI_START)) IS NULL " & _
						"OR LAG(OPS_SCI_END) OVER (PARTITION BY OPS_USR_ID ORDER BY CONNECT_BY_ROOT(OPS_SCI_START)) <> CONNECT_BY_ROOT(OPS_SCI_START) THEN 1 " & _
						"ELSE 0 " & _
						"END START_FLAG " & _
						"FROM " & _
						"( " & _
							"SELECT OPS_SCI_OPS_USR_ID OPS_USR_ID, " & _
							"DECODE(OPS_SCI_TYPE,'LNCH','LUNCH','LNFL','LUNCH','PHONE') SCHEDULE_TYPE, " & _
							"OPS_SCI_START, " & _
							"OPS_SCI_END, " & _
							"CASE " & _
								"WHEN LAG(OPS_SCI_END) OVER (PARTITION BY OPS_SCI_OPS_USR_ID ORDER BY OPS_SCI_START) IS NULL " & _
								"OR LAG(OPS_SCI_END) OVER (PARTITION BY OPS_SCI_OPS_USR_ID ORDER BY OPS_SCI_START) <> OPS_SCI_START " & _
								"OR LAG(DECODE(OPS_SCI_TYPE,'LNCH','LUNCH','LNFL','LUNCH','PHONE')) OVER (PARTITION BY OPS_SCI_OPS_USR_ID ORDER BY OPS_SCI_START) <> DECODE(OPS_SCI_TYPE,'LNCH','LUNCH','LNFL','LUNCH','PHONE') THEN 1 " & _
								"ELSE 0 " & _
							"END START_FLAG " & _
							"FROM OPS_SCHEDULE_INFO " & _
							"WHERE TO_DATE(OPS_SCI_START) = TO_DATE(?,'MM/DD/YYYY') " & _
							"AND OPS_SCI_STATUS = 'APP' " & _
							"AND OPS_SCI_TYPE IN ('BASE','PICK','ADDT','EXTD','NEWH','TRAN','PRES','MEET','PROJ','WFHU','LNCH','LNFL') " & _
							"AND OPS_SCI_START <> OPS_SCI_END " & _
							"AND OPS_SCI_OPS_USR_ID IN " & _
							"( " & _
								"SELECT DISTINCT OPS_SCI_OPS_USR_ID " & _
								"FROM OPS_SCHEDULE_INFO " & _
								"JOIN RES_ROUTING " & _
								"ON OPS_SCI_OPS_USR_ID = RES_RTE_OPS_USR_ID " & _
								"AND RES_RTE_YEAR = TO_CHAR(CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE)-(6/24),'YYYY') " & _
								"AND RES_RTE_MONTH = TO_CHAR(CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE)-(6/24),'MM') " & _
								"WHERE TO_DATE(OPS_SCI_START) = TO_DATE(?,'MM/DD/YYYY') " & _
								"AND OPS_SCI_STATUS = 'SUB' " & _
								"AND OPS_SCI_OPS_USR_TYPE = 'RES' " & _
								"AND OPS_SCI_TYPE IN ('CDUN','CDPT') " & _
								"AND RES_RTE_RES_RTG_ID IN (1,2,3) " & _
								"AND CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE) < OPS_SCI_END " & _
							") " & _
						") " & _
						"WHERE CONNECT_BY_ISLEAF = 1 " & _
						"START WITH START_FLAG = 1 " & _
						"CONNECT BY OPS_USR_ID = PRIOR OPS_USR_ID " & _
						"AND OPS_SCI_START = PRIOR OPS_SCI_END " & _
						"AND SCHEDULE_TYPE = PRIOR SCHEDULE_TYPE " & _
					") " & _
					"WHERE START_FLAG <> -1 " & _
				") " & _
				"WHERE CONNECT_BY_ISLEAF = 1 " & _
				"START WITH START_FLAG = 1 " & _
				"CONNECT BY OPS_USR_ID = PRIOR OPS_USR_ID " & _
				"AND OPS_SCI_START = PRIOR OPS_SCI_END " & _
			")SCHED " & _
			"ON CD.OPS_USR_ID = SCHED.OPS_USR_ID " & _
			"AND CD_START <= SCHEDULE_END " & _
			"AND CD_END >= SCHEDULE_START " & _
			"JOIN " & _
			"( " & _
				"SELECT " & _
				"OPS_USD_OPS_USR_ID OPS_USR_ID, " & _
				"CASE WHEN NVL(EVAL_SCORE,3) >= 3.25 THEN 1 ELSE 0 END EVAL_CHECK, " & _
				"CASE WHEN REDUCE_HOURS - NVL(UNPAID_HOURS,0) >= 4 THEN 1 ELSE 0 END UNPAID_CHECK, " & _
				"LEAST(GREATEST(NVL(REDUCE_HOURS,0) - NVL(UNPAID_HOURS,0),0),OPS_USD_SCH_HOURS) UNP_REMAINING, " & _
				"DECODE(OPS_ASN_OPS_ASM_ID,5,0,43,0,1) EPI_CHECK, " & _
				"OPS_ASN_OPS_ASM_ID " & _
				"FROM " & _
				"( " & _
					"SELECT " & _
					"OPS_USD_OPS_USR_ID, " & _
					"OPS_USD_SCH_HOURS " & _
					"FROM OPS_USER_DETAIL " & _
					"WHERE TO_DATE(?,'MM/DD/YYYY') BETWEEN OPS_USD_EFF_DATE AND OPS_USD_DIS_DATE " & _
					"AND OPS_USD_OPS_USR_ID IN " & _
					"( " & _
						"SELECT DISTINCT OPS_SCI_OPS_USR_ID " & _
						"FROM OPS_SCHEDULE_INFO " & _
						"JOIN RES_ROUTING " & _
						"ON OPS_SCI_OPS_USR_ID = RES_RTE_OPS_USR_ID " & _
						"AND RES_RTE_YEAR = TO_CHAR(CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE)-(6/24),'YYYY') " & _
						"AND RES_RTE_MONTH = TO_CHAR(CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE)-(6/24),'MM') " & _
						"WHERE TO_DATE(OPS_SCI_START) = TO_DATE(?,'MM/DD/YYYY') " & _
						"AND OPS_SCI_STATUS = 'SUB' " & _
						"AND OPS_SCI_OPS_USR_TYPE = 'RES' " & _
						"AND OPS_SCI_TYPE IN ('CDUN','CDPT') " & _
						"AND RES_RTE_RES_RTG_ID IN (1,2,3) " & _
						"AND CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE) < OPS_SCI_END " & _
					") " & _
				") " & _
				"LEFT JOIN " & _
				"( " & _
					"SELECT OPS_QUM_AGT_OPS_USR_ID, " & _
					"ROUND(AVG(OPS_QUM_SCORE),3) EVAL_SCORE " & _
					"FROM " & _
					"( " & _
						"SELECT " & _
						"OPS_QUM_AGT_OPS_USR_ID, " & _
						"OPS_QUM_SCORE, " & _
						"ROW_NUMBER() OVER (PARTITION BY OPS_QUM_AGT_OPS_USR_ID ORDER BY OPS_QUM_YEAR DESC, OPS_QUM_MONTH DESC) EVAL_NUM " & _
						"FROM OPS_QUALITY_MASTER " & _
						"JOIN OPS_FORM_MASTER " & _
						"ON OPS_QFM_ID = OPS_QUM_OPS_QFM_ID " & _
						"AND UPPER(OPS_QFM_NAME) LIKE '%MONTHLY EVALUATION' " & _
						"WHERE OPS_QUM_STATUS = 'COM' " & _
						"AND OPS_QUM_AGT_OPS_USR_ID IN " & _
						"( " & _
							"SELECT DISTINCT OPS_SCI_OPS_USR_ID " & _
							"FROM OPS_SCHEDULE_INFO " & _
							"JOIN RES_ROUTING " & _
							"ON OPS_SCI_OPS_USR_ID = RES_RTE_OPS_USR_ID " & _
							"AND RES_RTE_YEAR = TO_CHAR(CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE)-(6/24),'YYYY') " & _
							"AND RES_RTE_MONTH = TO_CHAR(CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE)-(6/24),'MM') " & _
							"WHERE TO_DATE(OPS_SCI_START) = TO_DATE(?,'MM/DD/YYYY') " & _
							"AND OPS_SCI_STATUS = 'SUB' " & _
							"AND OPS_SCI_OPS_USR_TYPE = 'RES' " & _
							"AND OPS_SCI_TYPE IN ('CDUN','CDPT') " & _
							"AND RES_RTE_RES_RTG_ID IN (1,2,3) " & _
							"AND CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE) < OPS_SCI_END " & _
						") " & _
					") " & _
					"WHERE EVAL_NUM <= 3 " & _
					"GROUP BY OPS_QUM_AGT_OPS_USR_ID " & _
				") " & _
				"ON OPS_USD_OPS_USR_ID = OPS_QUM_AGT_OPS_USR_ID " & _
				"LEFT JOIN " & _
				"( " & _
					"SELECT " & _
					"OPS_SCI_OPS_USR_ID, " & _
					"ROUND(SUM(24*(OPS_SCI_END-OPS_SCI_START)),1) UNPAID_HOURS " & _
					"FROM OPS_SCHEDULE_INFO		 " & _
					"WHERE OPS_SCI_STATUS = 'APP' " & _
					"AND REGEXP_LIKE(OPS_SCI_TYPE,'SLIP|HOLU|[^FM]UN$') " & _
					"AND TO_DATE(OPS_SCI_START) BETWEEN TO_DATE(?,'MM/DD/YYYY') - TO_CHAR(TO_DATE(?,'MM/DD/YYYY') ,'D') + 1 AND TO_DATE(?,'MM/DD/YYYY') - TO_CHAR(TO_DATE(?,'MM/DD/YYYY') ,'D') + 7 " & _
					"AND OPS_SCI_OPS_USR_ID IN " & _
					"( " & _
						"SELECT DISTINCT OPS_SCI_OPS_USR_ID " & _
						"FROM OPS_SCHEDULE_INFO " & _
						"JOIN RES_ROUTING " & _
						"ON OPS_SCI_OPS_USR_ID = RES_RTE_OPS_USR_ID " & _
						"AND RES_RTE_YEAR = TO_CHAR(CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE)-(6/24),'YYYY') " & _
						"AND RES_RTE_MONTH = TO_CHAR(CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE)-(6/24),'MM') " & _
						"WHERE TO_DATE(OPS_SCI_START) = TO_DATE(?,'MM/DD/YYYY') " & _
						"AND OPS_SCI_STATUS = 'SUB' " & _
						"AND OPS_SCI_OPS_USR_TYPE = 'RES' " & _
						"AND OPS_SCI_TYPE IN ('CDUN','CDPT') " & _
						"AND RES_RTE_RES_RTG_ID IN (1,2,3) " & _
						"AND CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE) < OPS_SCI_END " & _
					") " & _
					"GROUP BY OPS_SCI_OPS_USR_ID " & _
				") " & _
				"ON OPS_USD_OPS_USR_ID = OPS_SCI_OPS_USR_ID " & _
				"LEFT JOIN " & _
				"( " & _
					"SELECT " & _
					"REGEXP_SUBSTR(OPS_PAR_VALUE,'[^;]+',1,1) SCHEDULED_HOURS_MIN, " & _
					"REGEXP_SUBSTR(OPS_PAR_VALUE,'[^;]+',1,2) SCHEDULED_HOURS_MAX, " & _
					"REGEXP_SUBSTR(OPS_PAR_VALUE,'[^;]+',1,3) EVAL_MIN, " & _
					"REGEXP_SUBSTR(OPS_PAR_VALUE,'[^;]+',1,4) EVAL_MAX, " & _
					"REGEXP_SUBSTR(OPS_PAR_VALUE,'[^;]+',1,5) REDUCE_HOURS, " & _
					"OPS_PAR_EFF_DATE, " & _
					"OPS_PAR_DIS_DATE " & _
					"FROM OPS_PARAMETER " & _
					"WHERE OPS_PAR_CODE = 'REDUCE_LIMIT' " & _
					"AND OPS_PAR_PARENT_TYPE = 'RES' " & _
				") " & _
				"ON GREATEST(OPS_USD_SCH_HOURS,0.1) > SCHEDULED_HOURS_MIN " & _
				"AND GREATEST(OPS_USD_SCH_HOURS,0.1) <= SCHEDULED_HOURS_MAX " & _
				"AND LEAST(NVL(EVAL_SCORE,3),4.999) >= EVAL_MIN " & _
				"AND LEAST(NVL(EVAL_SCORE,3),4.999) < EVAL_MAX " & _
				"AND TO_DATE(?,'MM/DD/YYYY') BETWEEN OPS_PAR_EFF_DATE AND OPS_PAR_DIS_DATE " & _
				"LEFT JOIN " & _
				"( " & _
					"SELECT " & _
					"OPS_ASN_OPS_USR_ID, " & _
					"MAX(OPS_ASN_OPS_ASM_ID) OPS_ASN_OPS_ASM_ID " & _
					"FROM OPS_ASSIGNMENT " & _
					"WHERE OPS_ASN_OPS_ASM_ID IN (1,2,3,4,5,43) " & _
					"AND TO_DATE(?,'MM/DD/YYYY') BETWEEN OPS_ASN_EFF_DATE AND OPS_ASN_DIS_DATE " & _
					"AND OPS_ASN_OPS_USR_ID IN " & _
					"( " & _
						"SELECT DISTINCT OPS_SCI_OPS_USR_ID " & _
						"FROM OPS_SCHEDULE_INFO " & _
						"JOIN RES_ROUTING " & _
						"ON OPS_SCI_OPS_USR_ID = RES_RTE_OPS_USR_ID " & _
						"AND RES_RTE_YEAR = TO_CHAR(CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE)-(6/24),'YYYY') " & _
						"AND RES_RTE_MONTH = TO_CHAR(CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE)-(6/24),'MM') " & _
						"WHERE TO_DATE(OPS_SCI_START) = TO_DATE(?,'MM/DD/YYYY') " & _
						"AND OPS_SCI_STATUS = 'SUB' " & _
						"AND OPS_SCI_OPS_USR_TYPE = 'RES' " & _
						"AND OPS_SCI_TYPE IN ('CDUN','CDPT') " & _
						"AND RES_RTE_RES_RTG_ID IN (1,2,3) " & _
						"AND CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE) < OPS_SCI_END " & _
					") " & _
					"GROUP BY OPS_ASN_OPS_USR_ID " & _
				") " & _
				"ON OPS_USD_OPS_USR_ID = OPS_ASN_OPS_USR_ID " & _
			")CONDITIONS " & _
			"ON CD.OPS_USR_ID = CONDITIONS.OPS_USR_ID " & _
			"WHERE LEAST(CD_END,SCHEDULE_END) > GREATEST(CD_START,SCHEDULE_START,TO_DATE(CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE)) + ROUND(TO_CHAR(CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE),'SSSSS')/360)/240) " & _
		")CD " & _
		"JOIN OPS_USER_DETAIL " & _
		"ON CD.OPS_USR_ID = OPS_USD_OPS_USR_ID " & _
		"AND TO_DATE(CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE)) BETWEEN OPS_USD_EFF_DATE AND OPS_USD_DIS_DATE " & _
		"JOIN OPS_USER AGT " & _
		"ON CD.OPS_USR_ID = AGT.OPS_USR_ID " & _
		"JOIN OPS_USER SUP " & _
		"ON SUP.OPS_USR_ID = OPS_USD_SUPERVISOR " & _
		"LEFT JOIN " & _
		"( " & _
			"SELECT DISTINCT TO_NUMBER(TRIM(REGEXP_SUBSTR(RES_DLN_TEXT,'[^-]+',1,1))) NOTE_USR_ID " & _
			"FROM RES_DAILY_STATS_NOTES " & _
			"WHERE " & _
			"( " & _
				"( " & _
					"RES_DLN_DATE = TO_DATE(?,'MM/DD/YYYY') " & _
					"AND " & _
					"( " & _
						"TRIM(RES_DLN_TYPE) IN ('LATE','FLEX','SHFT','STRT','END','NFLX','OFLX','GAP','LMIN','OLAP','ABS','FWP','OTH','OUT','WFH','NA') " & _
						"OR " & _
						"( " & _
							"TRIM(RES_DLN_TYPE) = 'LWAV' " & _
							"AND DECODE(INSTR(RES_DLN_TEXT,'-'),0,NULL,TRIM(SUBSTR(RES_DLN_TEXT,INSTR(RES_DLN_TEXT,'-')+1))) IS NOT NULL " & _
						") " & _
					") " & _
				") " & _
				"OR " & _
				"( " & _
					"RES_DLN_DATE BETWEEN TO_DATE(?,'MM/DD/YYYY') - TO_CHAR(TO_DATE(?,'MM/DD/YYYY'),'D') + 1 AND TO_DATE(?,'MM/DD/YYYY') - TO_CHAR(TO_DATE(?,'MM/DD/YYYY'),'D') + 7 " & _
					"AND TRIM(RES_DLN_TYPE) = 'BWHC' " & _
				") " & _
			") " & _
		") " & _
		"ON CD.OPS_USR_ID = NOTE_USR_ID " & _
		"LEFT JOIN " & _
		"( " & _
			"SELECT DISTINCT TO_NUMBER(TRIM(REGEXP_SUBSTR(RES_DLN_TEXT,'[^-]+',1,1))) WAIVER_USR_ID " & _
			"FROM RES_DAILY_STATS_NOTES " & _
			"WHERE RES_DLN_DATE = TO_DATE(?,'MM/DD/YYYY') " & _
			"AND TRIM(RES_DLN_TYPE) = 'LWAV' " & _
		") " & _
		"ON CD.OPS_USR_ID = WAIVER_USR_ID " & _
		"WHERE CD_COUNT = 1 " & _
	")"
	
	SQLPendingSRV = "SELECT " & _
	"DECODE(COUNT(*) OVER (PARTITION BY PRIORITY),1,NULL,'T-') || TO_CHAR(TO_DATE(PRIORITY,'J'),'fmjth') PRIORITY, " & _
	"CD_START, " & _
	"CD_END, " & _
	"USE_AGENT, " & _
	"AGENT_NAME, " & _
	"SUPERVISOR_NAME, " & _
	"USE_WORKGROUP, " & _
	"USE_CLASS, " & _
	"USE_LOCATION, " & _
	"NOTE_BOOL, " & _
	"WAIVER_BOOL, " & _
	"UNP_REMAINING, " & _
	"AGENT_COUNT " & _
	"FROM " & _
	"( " & _
		"SELECT " & _
		"RANK() OVER (ORDER BY UNPAID_CHECK DESC, EVAL_CHECK DESC, CD_END, CDPT_CHECK DESC) PRIORITY, " & _
		"GREATEST(CD_START,TO_DATE(CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE)) + ROUND(TO_CHAR(CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE),'SSSSS')/360)/240) CD_START, " & _
		"CD_END, " & _
		"AGT.OPS_USR_ID USE_AGENT, " & _
		"AGT.OPS_USR_NAME AGENT_NAME, " & _
		"SUP.OPS_USR_NAME SUPERVISOR_NAME, " & _
		"'Elite Service' USE_WORKGROUP, " & _
		"DECODE(OPS_USD_CLASS,'RGFT','Reg Full-Time','RGPT','Reg Part-time','PT<30','PT Less Than 30','LEAVE','On Leave') USE_CLASS, " & _
		"DECODE(OPS_USD_LOCATION,'MOT','In-House','WFH','Work From Home','WFD','Work From Distance') USE_LOCATION, " & _
		"NVL2(NOTE_USR_ID,1,0) NOTE_BOOL, " & _
		"NVL2(WAIVER_USR_ID,1,0) WAIVER_BOOL, " & _
		"UNP_REMAINING, " & _
		"COUNT(*) OVER () AGENT_COUNT " & _
		"FROM " & _
		"( " & _
			"SELECT " & _
			"CD.OPS_USR_ID, " & _
			"GREATEST(CD_START,SCHEDULE_START) CD_START, " & _
			"LEAST(CD_END,SCHEDULE_END) CD_END, " & _
			"CDPT_CHECK, " & _
			"CASE WHEN 24*(LEAST(CD_END,SCHEDULE_END) - CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE)) < 1 THEN 1 ELSE EVAL_CHECK END EVAL_CHECK, " & _
			"UNPAID_CHECK, " & _
			"UNP_REMAINING, " & _
			"COUNT(*) OVER (PARTITION BY CD.OPS_USR_ID ORDER BY GREATEST(CD_START,SCHEDULE_START), LEAST(CD_END,SCHEDULE_END)) CD_COUNT " & _
			"FROM " & _
			"( " & _
				"SELECT " & _
				"OPS_USR_ID, " & _
				"LEAST(CONNECT_BY_ROOT(CDPT_CHECK),CDPT_CHECK) CDPT_CHECK, " & _
				"CONNECT_BY_ROOT(OPS_SCI_START) CD_START, " & _
				"OPS_SCI_END CD_END " & _
				"FROM " & _
				"( " & _
					"SELECT " & _
					"OPS_USR_ID, " & _
					"CDPT_CHECK, " & _
					"SCHEDULE_TYPE, " & _
					"OPS_SCI_START, " & _
					"OPS_SCI_END, " & _
					"CASE " & _
					"WHEN SCHEDULE_TYPE = 'LUNCH' THEN 0 " & _
					"WHEN LAG(START_FLAG) OVER (PARTITION BY OPS_USR_ID ORDER BY OPS_SCI_START) = 1 " & _
					"AND LAG(SCHEDULE_TYPE) OVER (PARTITION BY OPS_USR_ID ORDER BY OPS_SCI_START) = 'LUNCH' " & _
					"AND LAG(OPS_SCI_END) OVER (PARTITION BY OPS_USR_ID ORDER BY OPS_SCI_START) = OPS_SCI_START THEN 1 " & _
					"ELSE START_FLAG " & _
					"END START_FLAG " & _
					"FROM " & _
					"( " & _
						"SELECT OPS_USR_ID, " & _
						"CDPT_CHECK, " & _
						"SCHEDULE_TYPE, " & _
						"CONNECT_BY_ROOT(OPS_SCI_START) OPS_SCI_START, " & _
						"OPS_SCI_END, " & _
						"CASE " & _
						"WHEN LEAD(OPS_SCI_END) OVER (PARTITION BY OPS_USR_ID ORDER BY CONNECT_BY_ROOT(OPS_SCI_START)) IS NULL " & _
						"AND SCHEDULE_TYPE = 'LUNCH' THEN -1 " & _
						"WHEN LEAD(CONNECT_BY_ROOT(OPS_SCI_START)) OVER (PARTITION BY OPS_USR_ID ORDER BY CONNECT_BY_ROOT(OPS_SCI_START)) <> OPS_SCI_END " & _
						"AND SCHEDULE_TYPE = 'LUNCH' THEN -1 " & _
						"WHEN LAG(OPS_SCI_END) OVER (PARTITION BY OPS_USR_ID ORDER BY CONNECT_BY_ROOT(OPS_SCI_START)) IS NULL " & _
						"OR LAG(OPS_SCI_END) OVER (PARTITION BY OPS_USR_ID ORDER BY CONNECT_BY_ROOT(OPS_SCI_START)) <> CONNECT_BY_ROOT(OPS_SCI_START) THEN 1 " & _
						"ELSE 0 " & _
						"END START_FLAG " & _
						"FROM " & _
						"( " & _
							"SELECT OPS_SCI_OPS_USR_ID OPS_USR_ID, " & _
							"DECODE(OPS_SCI_TYPE,'CDPT',1,0) CDPT_CHECK, " & _
							"DECODE(OPS_SCI_TYPE,'LNCH','LUNCH','LNFL','LUNCH','CD') SCHEDULE_TYPE, " & _
							"OPS_SCI_START, " & _
							"OPS_SCI_END, " & _
							"CASE " & _
								"WHEN LAG(OPS_SCI_END) OVER (PARTITION BY OPS_SCI_OPS_USR_ID ORDER BY OPS_SCI_START) IS NULL " & _
								"OR LAG(OPS_SCI_END) OVER (PARTITION BY OPS_SCI_OPS_USR_ID ORDER BY OPS_SCI_START) <> OPS_SCI_START " & _
								"OR LAG(DECODE(OPS_SCI_TYPE,'LNCH','LUNCH','LNFL','LUNCH','CD')) OVER (PARTITION BY OPS_SCI_OPS_USR_ID ORDER BY OPS_SCI_START) <> DECODE(OPS_SCI_TYPE,'LNCH','LUNCH','LNFL','LUNCH','CD') THEN 1 " & _
								"ELSE 0 " & _
							"END START_FLAG " & _
							"FROM OPS_SCHEDULE_INFO " & _
							"WHERE TO_DATE(OPS_SCI_START) = TO_DATE(?,'MM/DD/YYYY') " & _
							"AND " & _
							"( " & _
								"( " & _
									"OPS_SCI_STATUS = 'SUB' " & _
									"AND OPS_SCI_TYPE IN ('CDUN','CDPT') " & _
								") " & _
								"OR " & _
								"( " & _
									"OPS_SCI_STATUS = 'APP' " & _
									"AND OPS_SCI_TYPE IN ('LNCH','LNFL') " & _
								") " & _
							") " & _
							"AND OPS_SCI_START <> OPS_SCI_END " & _
							"AND CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE) < OPS_SCI_END " & _
							"AND OPS_SCI_OPS_USR_ID IN " & _
							"( " & _
								"SELECT DISTINCT OPS_SCI_OPS_USR_ID " & _
								"FROM OPS_SCHEDULE_INFO " & _
								"JOIN RES_ROUTING " & _
								"ON OPS_SCI_OPS_USR_ID = RES_RTE_OPS_USR_ID " & _
								"AND RES_RTE_YEAR = TO_CHAR(CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE)-(6/24),'YYYY') " & _
								"AND RES_RTE_MONTH = TO_CHAR(CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE)-(6/24),'MM') " & _
								"WHERE TO_DATE(OPS_SCI_START) = TO_DATE(?,'MM/DD/YYYY') " & _
								"AND OPS_SCI_STATUS = 'SUB' " & _
								"AND OPS_SCI_OPS_USR_TYPE = 'RES' " & _
								"AND OPS_SCI_TYPE IN ('CDUN','CDPT') " & _
								"AND RES_RTE_RES_RTG_ID = 10 " & _
								"AND CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE) < OPS_SCI_END " & _
							") " & _
						") " & _
						"WHERE CONNECT_BY_ISLEAF = 1 " & _
						"START WITH START_FLAG = 1 " & _
						"CONNECT BY OPS_USR_ID = PRIOR OPS_USR_ID " & _
						"AND OPS_SCI_START = PRIOR OPS_SCI_END " & _
						"AND SCHEDULE_TYPE = PRIOR SCHEDULE_TYPE " & _
					") " & _
					"WHERE START_FLAG <> -1 " & _
				") " & _
				"WHERE CONNECT_BY_ISLEAF = 1 " & _
				"START WITH START_FLAG = 1 " & _
				"CONNECT BY OPS_USR_ID = PRIOR OPS_USR_ID " & _
				"AND OPS_SCI_START = PRIOR OPS_SCI_END " & _
			")CD " & _
			"JOIN " & _
			"( " & _
				"SELECT " & _
				"OPS_USR_ID, " & _
				"CONNECT_BY_ROOT(OPS_SCI_START) SCHEDULE_START, " & _
				"OPS_SCI_END SCHEDULE_END " & _
				"FROM " & _
				"( " & _
					"SELECT " & _
					"OPS_USR_ID, " & _
					"SCHEDULE_TYPE, " & _
					"OPS_SCI_START, " & _
					"OPS_SCI_END, " & _
					"CASE " & _
					"WHEN SCHEDULE_TYPE = 'LUNCH' THEN 0 " & _
					"WHEN LAG(START_FLAG) OVER (PARTITION BY OPS_USR_ID ORDER BY OPS_SCI_START) = 1 " & _
					"AND LAG(SCHEDULE_TYPE) OVER (PARTITION BY OPS_USR_ID ORDER BY OPS_SCI_START) = 'LUNCH' " & _
					"AND LAG(OPS_SCI_END) OVER (PARTITION BY OPS_USR_ID ORDER BY OPS_SCI_START) = OPS_SCI_START THEN 1 " & _
					"ELSE START_FLAG " & _
					"END START_FLAG " & _
					"FROM " & _
					"( " & _
						"SELECT OPS_USR_ID, " & _
						"SCHEDULE_TYPE, " & _
						"CONNECT_BY_ROOT(OPS_SCI_START) OPS_SCI_START, " & _
						"OPS_SCI_END, " & _
						"CASE " & _
						"WHEN LEAD(OPS_SCI_END) OVER (PARTITION BY OPS_USR_ID ORDER BY CONNECT_BY_ROOT(OPS_SCI_START)) IS NULL " & _
						"AND SCHEDULE_TYPE = 'LUNCH' THEN -1 " & _
						"WHEN LEAD(CONNECT_BY_ROOT(OPS_SCI_START)) OVER (PARTITION BY OPS_USR_ID ORDER BY CONNECT_BY_ROOT(OPS_SCI_START)) <> OPS_SCI_END " & _
						"AND SCHEDULE_TYPE = 'LUNCH' THEN -1 " & _
						"WHEN LAG(OPS_SCI_END) OVER (PARTITION BY OPS_USR_ID ORDER BY CONNECT_BY_ROOT(OPS_SCI_START)) IS NULL " & _
						"OR LAG(OPS_SCI_END) OVER (PARTITION BY OPS_USR_ID ORDER BY CONNECT_BY_ROOT(OPS_SCI_START)) <> CONNECT_BY_ROOT(OPS_SCI_START) THEN 1 " & _
						"ELSE 0 " & _
						"END START_FLAG " & _
						"FROM " & _
						"( " & _
							"SELECT OPS_SCI_OPS_USR_ID OPS_USR_ID, " & _
							"DECODE(OPS_SCI_TYPE,'LNCH','LUNCH','LNFL','LUNCH','PHONE') SCHEDULE_TYPE, " & _
							"OPS_SCI_START, " & _
							"OPS_SCI_END, " & _
							"CASE " & _
								"WHEN LAG(OPS_SCI_END) OVER (PARTITION BY OPS_SCI_OPS_USR_ID ORDER BY OPS_SCI_START) IS NULL " & _
								"OR LAG(OPS_SCI_END) OVER (PARTITION BY OPS_SCI_OPS_USR_ID ORDER BY OPS_SCI_START) <> OPS_SCI_START " & _
								"OR LAG(DECODE(OPS_SCI_TYPE,'LNCH','LUNCH','LNFL','LUNCH','PHONE')) OVER (PARTITION BY OPS_SCI_OPS_USR_ID ORDER BY OPS_SCI_START) <> DECODE(OPS_SCI_TYPE,'LNCH','LUNCH','LNFL','LUNCH','PHONE') THEN 1 " & _
								"ELSE 0 " & _
							"END START_FLAG " & _
							"FROM OPS_SCHEDULE_INFO " & _
							"WHERE TO_DATE(OPS_SCI_START) = TO_DATE(?,'MM/DD/YYYY') " & _
							"AND OPS_SCI_STATUS = 'APP' " & _
							"AND OPS_SCI_TYPE IN ('BASE','PICK','ADDT','EXTD','NEWH','TRAN','PRES','MEET','PROJ','WFHU','LNCH','LNFL') " & _
							"AND OPS_SCI_START <> OPS_SCI_END " & _
							"AND OPS_SCI_OPS_USR_ID IN " & _
							"( " & _
								"SELECT DISTINCT OPS_SCI_OPS_USR_ID " & _
								"FROM OPS_SCHEDULE_INFO " & _
								"JOIN RES_ROUTING " & _
								"ON OPS_SCI_OPS_USR_ID = RES_RTE_OPS_USR_ID " & _
								"AND RES_RTE_YEAR = TO_CHAR(CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE)-(6/24),'YYYY') " & _
								"AND RES_RTE_MONTH = TO_CHAR(CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE)-(6/24),'MM') " & _
								"WHERE TO_DATE(OPS_SCI_START) = TO_DATE(?,'MM/DD/YYYY') " & _
								"AND OPS_SCI_STATUS = 'SUB' " & _
								"AND OPS_SCI_OPS_USR_TYPE = 'RES' " & _
								"AND OPS_SCI_TYPE IN ('CDUN','CDPT') " & _
								"AND RES_RTE_RES_RTG_ID = 10 " & _
								"AND CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE) < OPS_SCI_END " & _
							") " & _
						") " & _
						"WHERE CONNECT_BY_ISLEAF = 1 " & _
						"START WITH START_FLAG = 1 " & _
						"CONNECT BY OPS_USR_ID = PRIOR OPS_USR_ID " & _
						"AND OPS_SCI_START = PRIOR OPS_SCI_END " & _
						"AND SCHEDULE_TYPE = PRIOR SCHEDULE_TYPE " & _
					") " & _
					"WHERE START_FLAG <> -1 " & _
				") " & _
				"WHERE CONNECT_BY_ISLEAF = 1 " & _
				"START WITH START_FLAG = 1 " & _
				"CONNECT BY OPS_USR_ID = PRIOR OPS_USR_ID " & _
				"AND OPS_SCI_START = PRIOR OPS_SCI_END " & _
			")SCHED " & _
			"ON CD.OPS_USR_ID = SCHED.OPS_USR_ID " & _
			"AND CD_START <= SCHEDULE_END " & _
			"AND CD_END >= SCHEDULE_START " & _
			"JOIN " & _
			"( " & _
				"SELECT " & _
				"OPS_USD_OPS_USR_ID OPS_USR_ID, " & _
				"CASE WHEN NVL(EVAL_SCORE,3) >= 3.25 THEN 1 ELSE 0 END EVAL_CHECK, " & _
				"CASE WHEN REDUCE_HOURS - NVL(UNPAID_HOURS,0) >= 4 THEN 1 ELSE 0 END UNPAID_CHECK, " & _
				"LEAST(GREATEST(NVL(REDUCE_HOURS,0) - NVL(UNPAID_HOURS,0),0),OPS_USD_SCH_HOURS) UNP_REMAINING " & _
				"FROM " & _
				"( " & _
					"SELECT " & _
					"OPS_USD_OPS_USR_ID, " & _
					"OPS_USD_SCH_HOURS " & _
					"FROM OPS_USER_DETAIL " & _
					"WHERE TO_DATE(?,'MM/DD/YYYY') BETWEEN OPS_USD_EFF_DATE AND OPS_USD_DIS_DATE " & _
					"AND OPS_USD_OPS_USR_ID IN " & _
					"( " & _
						"SELECT DISTINCT OPS_SCI_OPS_USR_ID " & _
						"FROM OPS_SCHEDULE_INFO " & _
						"JOIN RES_ROUTING " & _
						"ON OPS_SCI_OPS_USR_ID = RES_RTE_OPS_USR_ID " & _
						"AND RES_RTE_YEAR = TO_CHAR(CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE)-(6/24),'YYYY') " & _
						"AND RES_RTE_MONTH = TO_CHAR(CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE)-(6/24),'MM') " & _
						"WHERE TO_DATE(OPS_SCI_START) = TO_DATE(?,'MM/DD/YYYY') " & _
						"AND OPS_SCI_STATUS = 'SUB' " & _
						"AND OPS_SCI_OPS_USR_TYPE = 'RES' " & _
						"AND OPS_SCI_TYPE IN ('CDUN','CDPT') " & _
						"AND RES_RTE_RES_RTG_ID = 10 " & _
						"AND CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE) < OPS_SCI_END " & _
					") " & _
				") " & _
				"LEFT JOIN " & _
				"( " & _
					"SELECT OPS_QUM_AGT_OPS_USR_ID, " & _
					"ROUND(AVG(OPS_QUM_SCORE),3) EVAL_SCORE " & _
					"FROM " & _
					"( " & _
						"SELECT " & _
						"OPS_QUM_AGT_OPS_USR_ID, " & _
						"OPS_QUM_SCORE, " & _
						"ROW_NUMBER() OVER (PARTITION BY OPS_QUM_AGT_OPS_USR_ID ORDER BY OPS_QUM_YEAR DESC, OPS_QUM_MONTH DESC) EVAL_NUM " & _
						"FROM OPS_QUALITY_MASTER " & _
						"JOIN OPS_FORM_MASTER " & _
						"ON OPS_QFM_ID = OPS_QUM_OPS_QFM_ID " & _
						"AND UPPER(OPS_QFM_NAME) LIKE '%MONTHLY EVALUATION' " & _
						"WHERE OPS_QUM_STATUS = 'COM' " & _
						"AND OPS_QUM_AGT_OPS_USR_ID IN " & _
						"( " & _
							"SELECT DISTINCT OPS_SCI_OPS_USR_ID " & _
							"FROM OPS_SCHEDULE_INFO " & _
							"JOIN RES_ROUTING " & _
							"ON OPS_SCI_OPS_USR_ID = RES_RTE_OPS_USR_ID " & _
							"AND RES_RTE_YEAR = TO_CHAR(CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE)-(6/24),'YYYY') " & _
							"AND RES_RTE_MONTH = TO_CHAR(CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE)-(6/24),'MM') " & _
							"WHERE TO_DATE(OPS_SCI_START) = TO_DATE(?,'MM/DD/YYYY') " & _
							"AND OPS_SCI_STATUS = 'SUB' " & _
							"AND OPS_SCI_OPS_USR_TYPE = 'RES' " & _
							"AND OPS_SCI_TYPE IN ('CDUN','CDPT') " & _
							"AND RES_RTE_RES_RTG_ID = 10 " & _
							"AND CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE) < OPS_SCI_END " & _
						") " & _
					") " & _
					"WHERE EVAL_NUM <= 3 " & _
					"GROUP BY OPS_QUM_AGT_OPS_USR_ID " & _
				") " & _
				"ON OPS_USD_OPS_USR_ID = OPS_QUM_AGT_OPS_USR_ID " & _
				"LEFT JOIN " & _
				"( " & _
					"SELECT " & _
					"OPS_SCI_OPS_USR_ID, " & _
					"ROUND(SUM(24*(OPS_SCI_END-OPS_SCI_START)),1) UNPAID_HOURS " & _
					"FROM OPS_SCHEDULE_INFO		 " & _
					"WHERE OPS_SCI_STATUS = 'APP' " & _
					"AND REGEXP_LIKE(OPS_SCI_TYPE,'SLIP|HOLU|[^FM]UN$') " & _
					"AND TO_DATE(OPS_SCI_START) BETWEEN TO_DATE(?,'MM/DD/YYYY') - TO_CHAR(TO_DATE(?,'MM/DD/YYYY') ,'D') + 1 AND TO_DATE(?,'MM/DD/YYYY') - TO_CHAR(TO_DATE(?,'MM/DD/YYYY') ,'D') + 7 " & _
					"AND OPS_SCI_OPS_USR_ID IN " & _
					"( " & _
						"SELECT DISTINCT OPS_SCI_OPS_USR_ID " & _
						"FROM OPS_SCHEDULE_INFO " & _
						"JOIN RES_ROUTING " & _
						"ON OPS_SCI_OPS_USR_ID = RES_RTE_OPS_USR_ID " & _
						"AND RES_RTE_YEAR = TO_CHAR(CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE)-(6/24),'YYYY') " & _
						"AND RES_RTE_MONTH = TO_CHAR(CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE)-(6/24),'MM') " & _
						"WHERE TO_DATE(OPS_SCI_START) = TO_DATE(?,'MM/DD/YYYY') " & _
						"AND OPS_SCI_STATUS = 'SUB' " & _
						"AND OPS_SCI_OPS_USR_TYPE = 'RES' " & _
						"AND OPS_SCI_TYPE IN ('CDUN','CDPT') " & _
						"AND RES_RTE_RES_RTG_ID = 10 " & _
						"AND CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE) < OPS_SCI_END " & _
					") " & _
					"GROUP BY OPS_SCI_OPS_USR_ID " & _
				") " & _
				"ON OPS_USD_OPS_USR_ID = OPS_SCI_OPS_USR_ID " & _
				"LEFT JOIN " & _
				"( " & _
					"SELECT " & _
					"REGEXP_SUBSTR(OPS_PAR_VALUE,'[^;]+',1,1) SCHEDULED_HOURS_MIN, " & _
					"REGEXP_SUBSTR(OPS_PAR_VALUE,'[^;]+',1,2) SCHEDULED_HOURS_MAX, " & _
					"REGEXP_SUBSTR(OPS_PAR_VALUE,'[^;]+',1,3) EVAL_MIN, " & _
					"REGEXP_SUBSTR(OPS_PAR_VALUE,'[^;]+',1,4) EVAL_MAX, " & _
					"REGEXP_SUBSTR(OPS_PAR_VALUE,'[^;]+',1,5) REDUCE_HOURS, " & _
					"OPS_PAR_EFF_DATE, " & _
					"OPS_PAR_DIS_DATE " & _
					"FROM OPS_PARAMETER " & _
					"WHERE OPS_PAR_CODE = 'REDUCE_LIMIT' " & _
					"AND OPS_PAR_PARENT_TYPE = 'RES' " & _
				") " & _
				"ON GREATEST(OPS_USD_SCH_HOURS,0.1) > SCHEDULED_HOURS_MIN " & _
				"AND GREATEST(OPS_USD_SCH_HOURS,0.1) <= SCHEDULED_HOURS_MAX " & _
				"AND LEAST(NVL(EVAL_SCORE,3),4.999) >= EVAL_MIN " & _
				"AND LEAST(NVL(EVAL_SCORE,3),4.999) < EVAL_MAX " & _
				"AND TO_DATE(?,'MM/DD/YYYY') BETWEEN OPS_PAR_EFF_DATE AND OPS_PAR_DIS_DATE " & _
			")CONDITIONS " & _
			"ON CD.OPS_USR_ID = CONDITIONS.OPS_USR_ID " & _
			"WHERE LEAST(CD_END,SCHEDULE_END) > GREATEST(CD_START,SCHEDULE_START,TO_DATE(CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE)) + ROUND(TO_CHAR(CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE),'SSSSS')/360)/240) " & _
		")CD " & _
		"JOIN OPS_USER_DETAIL " & _
		"ON CD.OPS_USR_ID = OPS_USD_OPS_USR_ID " & _
		"AND TO_DATE(CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE)) BETWEEN OPS_USD_EFF_DATE AND OPS_USD_DIS_DATE " & _
		"JOIN OPS_USER AGT " & _
		"ON CD.OPS_USR_ID = AGT.OPS_USR_ID " & _
		"JOIN OPS_USER SUP " & _
		"ON SUP.OPS_USR_ID = OPS_USD_SUPERVISOR " & _
		"LEFT JOIN " & _
		"( " & _
			"SELECT DISTINCT TO_NUMBER(TRIM(REGEXP_SUBSTR(RES_DLN_TEXT,'[^-]+',1,1))) NOTE_USR_ID " & _
			"FROM RES_DAILY_STATS_NOTES " & _
			"WHERE " & _
			"( " & _
				"( " & _
					"RES_DLN_DATE = TO_DATE(?,'MM/DD/YYYY') " & _
					"AND " & _
					"( " & _
						"TRIM(RES_DLN_TYPE) IN ('LATE','FLEX','SHFT','STRT','END','NFLX','OFLX','GAP','LMIN','OLAP','ABS','FWP','OTH','OUT','WFH','NA') " & _
						"OR " & _
						"( " & _
							"TRIM(RES_DLN_TYPE) = 'LWAV' " & _
							"AND DECODE(INSTR(RES_DLN_TEXT,'-'),0,NULL,TRIM(SUBSTR(RES_DLN_TEXT,INSTR(RES_DLN_TEXT,'-')+1))) IS NOT NULL " & _
						") " & _
					") " & _
				") " & _
				"OR " & _
				"( " & _
					"RES_DLN_DATE BETWEEN TO_DATE(?,'MM/DD/YYYY') - TO_CHAR(TO_DATE(?,'MM/DD/YYYY'),'D') + 1 AND TO_DATE(?,'MM/DD/YYYY') - TO_CHAR(TO_DATE(?,'MM/DD/YYYY'),'D') + 7 " & _
					"AND TRIM(RES_DLN_TYPE) = 'BWHC' " & _
				") " & _
			") " & _
		") " & _
		"ON CD.OPS_USR_ID = NOTE_USR_ID " & _
		"LEFT JOIN " & _
		"( " & _
			"SELECT DISTINCT TO_NUMBER(TRIM(REGEXP_SUBSTR(RES_DLN_TEXT,'[^-]+',1,1))) WAIVER_USR_ID " & _
			"FROM RES_DAILY_STATS_NOTES " & _
			"WHERE RES_DLN_DATE = TO_DATE(?,'MM/DD/YYYY') " & _
			"AND TRIM(RES_DLN_TYPE) = 'LWAV' " & _
		") " & _
		"ON CD.OPS_USR_ID = WAIVER_USR_ID " & _
		"WHERE CD_COUNT = 1 " & _
	")"
	
	SQLPendingSPT = "SELECT " & _
	"DECODE(COUNT(*) OVER (PARTITION BY PRIORITY),1,NULL,'T-') || TO_CHAR(TO_DATE(PRIORITY,'J'),'fmjth') PRIORITY, " & _
	"CD_START, " & _
	"CD_END, " & _
	"USE_AGENT, " & _
	"AGENT_NAME, " & _
	"SUPERVISOR_NAME, " & _
	"USE_WORKGROUP, " & _
	"USE_CLASS, " & _
	"USE_LOCATION, " & _
	"NOTE_BOOL, " & _
	"WAIVER_BOOL, " & _
	"UNP_REMAINING, " & _
	"AGENT_COUNT " & _
	"FROM " & _
	"( " & _
		"SELECT " & _
		"RANK() OVER (ORDER BY UNPAID_CHECK DESC, EVAL_CHECK DESC, DECODE(RES_RTE_RES_RTG_ID,4,1,2), CD_END, CDPT_CHECK DESC) PRIORITY, " & _
		"GREATEST(CD_START,TO_DATE(CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE)) + ROUND(TO_CHAR(CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE),'SSSSS')/360)/240) CD_START, " & _
		"CD_END, " & _
		"AGT.OPS_USR_ID USE_AGENT, " & _
		"AGT.OPS_USR_NAME AGENT_NAME, " & _
		"SUP.OPS_USR_NAME SUPERVISOR_NAME, " & _
		"'SPT ' || DECODE(RES_RTE_RES_RTG_ID,13,'OSR',5,'ASR','VSS') || " & _
		"CASE " & _
			"WHEN RES_RTE_RES_RTG_ID = 5 AND OPS_ASN_OPS_ASM_ID = 41 THEN ' - Jira' " & _
			"WHEN RES_RTE_RES_RTG_ID = 5 AND OPS_ASN_OPS_ASM_ID = 45 THEN ' - TAS' " & _
		"END USE_WORKGROUP, " & _
		"DECODE(OPS_USD_CLASS,'RGFT','Reg Full-Time','RGPT','Reg Part-time','PT<30','PT Less Than 30','LEAVE','On Leave') USE_CLASS, " & _
		"DECODE(OPS_USD_LOCATION,'MOT','In-House','WFH','Work From Home','WFD','Work From Distance') USE_LOCATION, " & _
		"NVL2(NOTE_USR_ID,1,0) NOTE_BOOL, " & _
		"NVL2(WAIVER_USR_ID,1,0) WAIVER_BOOL, " & _
		"UNP_REMAINING, " & _
		"COUNT(*) OVER () AGENT_COUNT " & _
		"FROM " & _
		"( " & _
			"SELECT " & _
			"CD.OPS_USR_ID, " & _
			"GREATEST(CD_START,SCHEDULE_START) CD_START, " & _
			"LEAST(CD_END,SCHEDULE_END) CD_END, " & _
			"CDPT_CHECK, " & _
			"CASE WHEN 24*(LEAST(CD_END,SCHEDULE_END) - CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE)) < 1 THEN 1 ELSE EVAL_CHECK END EVAL_CHECK, " & _
			"UNPAID_CHECK, " & _
			"UNP_REMAINING, " & _
			"COUNT(*) OVER (PARTITION BY CD.OPS_USR_ID ORDER BY GREATEST(CD_START,SCHEDULE_START), LEAST(CD_END,SCHEDULE_END)) CD_COUNT " & _
			"FROM " & _
			"( " & _
				"SELECT " & _
				"OPS_USR_ID, " & _
				"LEAST(CONNECT_BY_ROOT(CDPT_CHECK),CDPT_CHECK) CDPT_CHECK, " & _
				"CONNECT_BY_ROOT(OPS_SCI_START) CD_START, " & _
				"OPS_SCI_END CD_END " & _
				"FROM " & _
				"( " & _
					"SELECT " & _
					"OPS_USR_ID, " & _
					"CDPT_CHECK, " & _
					"SCHEDULE_TYPE, " & _
					"OPS_SCI_START, " & _
					"OPS_SCI_END, " & _
					"CASE " & _
					"WHEN SCHEDULE_TYPE = 'LUNCH' THEN 0 " & _
					"WHEN LAG(START_FLAG) OVER (PARTITION BY OPS_USR_ID ORDER BY OPS_SCI_START) = 1 " & _
					"AND LAG(SCHEDULE_TYPE) OVER (PARTITION BY OPS_USR_ID ORDER BY OPS_SCI_START) = 'LUNCH' " & _
					"AND LAG(OPS_SCI_END) OVER (PARTITION BY OPS_USR_ID ORDER BY OPS_SCI_START) = OPS_SCI_START THEN 1 " & _
					"ELSE START_FLAG " & _
					"END START_FLAG " & _
					"FROM " & _
					"( " & _
						"SELECT OPS_USR_ID, " & _
						"CDPT_CHECK, " & _
						"SCHEDULE_TYPE, " & _
						"CONNECT_BY_ROOT(OPS_SCI_START) OPS_SCI_START, " & _
						"OPS_SCI_END, " & _
						"CASE " & _
						"WHEN LEAD(OPS_SCI_END) OVER (PARTITION BY OPS_USR_ID ORDER BY CONNECT_BY_ROOT(OPS_SCI_START)) IS NULL " & _
						"AND SCHEDULE_TYPE = 'LUNCH' THEN -1 " & _
						"WHEN LEAD(CONNECT_BY_ROOT(OPS_SCI_START)) OVER (PARTITION BY OPS_USR_ID ORDER BY CONNECT_BY_ROOT(OPS_SCI_START)) <> OPS_SCI_END " & _
						"AND SCHEDULE_TYPE = 'LUNCH' THEN -1 " & _
						"WHEN LAG(OPS_SCI_END) OVER (PARTITION BY OPS_USR_ID ORDER BY CONNECT_BY_ROOT(OPS_SCI_START)) IS NULL " & _
						"OR LAG(OPS_SCI_END) OVER (PARTITION BY OPS_USR_ID ORDER BY CONNECT_BY_ROOT(OPS_SCI_START)) <> CONNECT_BY_ROOT(OPS_SCI_START) THEN 1 " & _
						"ELSE 0 " & _
						"END START_FLAG " & _
						"FROM " & _
						"( " & _
							"SELECT OPS_SCI_OPS_USR_ID OPS_USR_ID, " & _
							"DECODE(OPS_SCI_TYPE,'CDPT',1,0) CDPT_CHECK, " & _
							"DECODE(OPS_SCI_TYPE,'LNCH','LUNCH','LNFL','LUNCH','CD') SCHEDULE_TYPE, " & _
							"OPS_SCI_START, " & _
							"OPS_SCI_END, " & _
							"CASE " & _
								"WHEN LAG(OPS_SCI_END) OVER (PARTITION BY OPS_SCI_OPS_USR_ID ORDER BY OPS_SCI_START) IS NULL " & _
								"OR LAG(OPS_SCI_END) OVER (PARTITION BY OPS_SCI_OPS_USR_ID ORDER BY OPS_SCI_START) <> OPS_SCI_START " & _
								"OR LAG(DECODE(OPS_SCI_TYPE,'LNCH','LUNCH','LNFL','LUNCH','CD')) OVER (PARTITION BY OPS_SCI_OPS_USR_ID ORDER BY OPS_SCI_START) <> DECODE(OPS_SCI_TYPE,'LNCH','LUNCH','LNFL','LUNCH','CD') THEN 1 " & _
								"ELSE 0 " & _
							"END START_FLAG " & _
							"FROM OPS_SCHEDULE_INFO " & _
							"WHERE TO_DATE(OPS_SCI_START) = TO_DATE(?,'MM/DD/YYYY') " & _
							"AND " & _
							"( " & _
								"( " & _
									"OPS_SCI_STATUS = 'SUB' " & _
									"AND OPS_SCI_TYPE IN ('CDUN','CDPT') " & _
								") " & _
								"OR " & _
								"( " & _
									"OPS_SCI_STATUS = 'APP' " & _
									"AND OPS_SCI_TYPE IN ('LNCH','LNFL') " & _
								") " & _
							") " & _
							"AND OPS_SCI_START <> OPS_SCI_END " & _
							"AND CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE) < OPS_SCI_END " & _
							"AND OPS_SCI_OPS_USR_ID IN " & _
							"( " & _
								"SELECT DISTINCT OPS_SCI_OPS_USR_ID " & _
								"FROM OPS_SCHEDULE_INFO " & _
								"JOIN RES_ROUTING " & _
								"ON OPS_SCI_OPS_USR_ID = RES_RTE_OPS_USR_ID " & _
								"AND RES_RTE_YEAR = TO_CHAR(CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE)-(6/24),'YYYY') " & _
								"AND RES_RTE_MONTH = TO_CHAR(CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE)-(6/24),'MM') " & _
								"WHERE TO_DATE(OPS_SCI_START) = TO_DATE(?,'MM/DD/YYYY') " & _
								"AND OPS_SCI_STATUS = 'SUB' " & _
								"AND OPS_SCI_OPS_USR_TYPE = 'RES' " & _
								"AND OPS_SCI_TYPE IN ('CDUN','CDPT') " & _
								"AND RES_RTE_RES_RTG_ID IN (4,5,13) " & _
								"AND CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE) < OPS_SCI_END " & _
							") " & _
						") " & _
						"WHERE CONNECT_BY_ISLEAF = 1 " & _
						"START WITH START_FLAG = 1 " & _
						"CONNECT BY OPS_USR_ID = PRIOR OPS_USR_ID " & _
						"AND OPS_SCI_START = PRIOR OPS_SCI_END " & _
						"AND SCHEDULE_TYPE = PRIOR SCHEDULE_TYPE " & _
					") " & _
					"WHERE START_FLAG <> -1 " & _
				") " & _
				"WHERE CONNECT_BY_ISLEAF = 1 " & _
				"START WITH START_FLAG = 1 " & _
				"CONNECT BY OPS_USR_ID = PRIOR OPS_USR_ID " & _
				"AND OPS_SCI_START = PRIOR OPS_SCI_END " & _
			")CD " & _
			"JOIN " & _
			"( " & _
				"SELECT " & _
				"OPS_USR_ID, " & _
				"CONNECT_BY_ROOT(OPS_SCI_START) SCHEDULE_START, " & _
				"OPS_SCI_END SCHEDULE_END " & _
				"FROM " & _
				"( " & _
					"SELECT " & _
					"OPS_USR_ID, " & _
					"SCHEDULE_TYPE, " & _
					"OPS_SCI_START, " & _
					"OPS_SCI_END, " & _
					"CASE " & _
					"WHEN SCHEDULE_TYPE = 'LUNCH' THEN 0 " & _
					"WHEN LAG(START_FLAG) OVER (PARTITION BY OPS_USR_ID ORDER BY OPS_SCI_START) = 1 " & _
					"AND LAG(SCHEDULE_TYPE) OVER (PARTITION BY OPS_USR_ID ORDER BY OPS_SCI_START) = 'LUNCH' " & _
					"AND LAG(OPS_SCI_END) OVER (PARTITION BY OPS_USR_ID ORDER BY OPS_SCI_START) = OPS_SCI_START THEN 1 " & _
					"ELSE START_FLAG " & _
					"END START_FLAG " & _
					"FROM " & _
					"( " & _
						"SELECT OPS_USR_ID, " & _
						"SCHEDULE_TYPE, " & _
						"CONNECT_BY_ROOT(OPS_SCI_START) OPS_SCI_START, " & _
						"OPS_SCI_END, " & _
						"CASE " & _
						"WHEN LEAD(OPS_SCI_END) OVER (PARTITION BY OPS_USR_ID ORDER BY CONNECT_BY_ROOT(OPS_SCI_START)) IS NULL " & _
						"AND SCHEDULE_TYPE = 'LUNCH' THEN -1 " & _
						"WHEN LEAD(CONNECT_BY_ROOT(OPS_SCI_START)) OVER (PARTITION BY OPS_USR_ID ORDER BY CONNECT_BY_ROOT(OPS_SCI_START)) <> OPS_SCI_END " & _
						"AND SCHEDULE_TYPE = 'LUNCH' THEN -1 " & _
						"WHEN LAG(OPS_SCI_END) OVER (PARTITION BY OPS_USR_ID ORDER BY CONNECT_BY_ROOT(OPS_SCI_START)) IS NULL " & _
						"OR LAG(OPS_SCI_END) OVER (PARTITION BY OPS_USR_ID ORDER BY CONNECT_BY_ROOT(OPS_SCI_START)) <> CONNECT_BY_ROOT(OPS_SCI_START) THEN 1 " & _
						"ELSE 0 " & _
						"END START_FLAG " & _
						"FROM " & _
						"( " & _
							"SELECT OPS_SCI_OPS_USR_ID OPS_USR_ID, " & _
							"DECODE(OPS_SCI_TYPE,'LNCH','LUNCH','LNFL','LUNCH','PHONE') SCHEDULE_TYPE, " & _
							"OPS_SCI_START, " & _
							"OPS_SCI_END, " & _
							"CASE " & _
								"WHEN LAG(OPS_SCI_END) OVER (PARTITION BY OPS_SCI_OPS_USR_ID ORDER BY OPS_SCI_START) IS NULL " & _
								"OR LAG(OPS_SCI_END) OVER (PARTITION BY OPS_SCI_OPS_USR_ID ORDER BY OPS_SCI_START) <> OPS_SCI_START " & _
								"OR LAG(DECODE(OPS_SCI_TYPE,'LNCH','LUNCH','LNFL','LUNCH','PHONE')) OVER (PARTITION BY OPS_SCI_OPS_USR_ID ORDER BY OPS_SCI_START) <> DECODE(OPS_SCI_TYPE,'LNCH','LUNCH','LNFL','LUNCH','PHONE') THEN 1 " & _
								"ELSE 0 " & _
							"END START_FLAG " & _
							"FROM OPS_SCHEDULE_INFO " & _
							"WHERE TO_DATE(OPS_SCI_START) = TO_DATE(?,'MM/DD/YYYY') " & _
							"AND OPS_SCI_STATUS = 'APP' " & _
							"AND OPS_SCI_TYPE IN ('BASE','PICK','ADDT','EXTD','NEWH','TRAN','PRES','MEET','PROJ','WFHU','LNCH','LNFL') " & _
							"AND OPS_SCI_START <> OPS_SCI_END " & _
							"AND OPS_SCI_OPS_USR_ID IN " & _
							"( " & _
								"SELECT DISTINCT OPS_SCI_OPS_USR_ID " & _
								"FROM OPS_SCHEDULE_INFO " & _
								"JOIN RES_ROUTING " & _
								"ON OPS_SCI_OPS_USR_ID = RES_RTE_OPS_USR_ID " & _
								"AND RES_RTE_YEAR = TO_CHAR(CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE)-(6/24),'YYYY') " & _
								"AND RES_RTE_MONTH = TO_CHAR(CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE)-(6/24),'MM') " & _
								"WHERE TO_DATE(OPS_SCI_START) = TO_DATE(?,'MM/DD/YYYY') " & _
								"AND OPS_SCI_STATUS = 'SUB' " & _
								"AND OPS_SCI_OPS_USR_TYPE = 'RES' " & _
								"AND OPS_SCI_TYPE IN ('CDUN','CDPT') " & _
								"AND RES_RTE_RES_RTG_ID IN (4,5,13) " & _
								"AND CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE) < OPS_SCI_END " & _
							") " & _
						") " & _
						"WHERE CONNECT_BY_ISLEAF = 1 " & _
						"START WITH START_FLAG = 1 " & _
						"CONNECT BY OPS_USR_ID = PRIOR OPS_USR_ID " & _
						"AND OPS_SCI_START = PRIOR OPS_SCI_END " & _
						"AND SCHEDULE_TYPE = PRIOR SCHEDULE_TYPE " & _
					") " & _
					"WHERE START_FLAG <> -1 " & _
				") " & _
				"WHERE CONNECT_BY_ISLEAF = 1 " & _
				"START WITH START_FLAG = 1 " & _
				"CONNECT BY OPS_USR_ID = PRIOR OPS_USR_ID " & _
				"AND OPS_SCI_START = PRIOR OPS_SCI_END " & _
			")SCHED " & _
			"ON CD.OPS_USR_ID = SCHED.OPS_USR_ID " & _
			"AND CD_START <= SCHEDULE_END " & _
			"AND CD_END >= SCHEDULE_START " & _
			"JOIN " & _
			"( " & _
				"SELECT " & _
				"OPS_USD_OPS_USR_ID OPS_USR_ID, " & _
				"OPS_USD_TEAM, " & _
				"CASE WHEN NVL(EVAL_SCORE,3) >= 3.25 THEN 1 ELSE 0 END EVAL_CHECK, " & _
				"CASE WHEN REDUCE_HOURS - NVL(UNPAID_HOURS,0) >= 4 THEN 1 ELSE 0 END UNPAID_CHECK, " & _
				"LEAST(GREATEST(NVL(REDUCE_HOURS,0) - NVL(UNPAID_HOURS,0),0),OPS_USD_SCH_HOURS) UNP_REMAINING " & _
				"FROM " & _
				"( " & _
					"SELECT " & _
					"OPS_USD_OPS_USR_ID, " & _
					"DECODE(OPS_USD_TEAM,'SRV','VSS','SPT','ASR','OSR','OSR','ASR') OPS_USD_TEAM, " & _
					"OPS_USD_SCH_HOURS " & _
					"FROM OPS_USER_DETAIL " & _
					"WHERE TO_DATE(?,'MM/DD/YYYY') BETWEEN OPS_USD_EFF_DATE AND OPS_USD_DIS_DATE " & _
					"AND OPS_USD_OPS_USR_ID IN " & _
					"( " & _
						"SELECT DISTINCT OPS_SCI_OPS_USR_ID " & _
						"FROM OPS_SCHEDULE_INFO " & _
						"JOIN RES_ROUTING " & _
						"ON OPS_SCI_OPS_USR_ID = RES_RTE_OPS_USR_ID " & _
						"AND RES_RTE_YEAR = TO_CHAR(CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE)-(6/24),'YYYY') " & _
						"AND RES_RTE_MONTH = TO_CHAR(CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE)-(6/24),'MM') " & _
						"WHERE TO_DATE(OPS_SCI_START) = TO_DATE(?,'MM/DD/YYYY') " & _
						"AND OPS_SCI_STATUS = 'SUB' " & _
						"AND OPS_SCI_OPS_USR_TYPE = 'RES' " & _
						"AND OPS_SCI_TYPE IN ('CDUN','CDPT') " & _
						"AND RES_RTE_RES_RTG_ID IN (4,5,13) " & _
						"AND CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE) < OPS_SCI_END " & _
					") " & _
				") " & _
				"LEFT JOIN " & _
				"( " & _
					"SELECT OPS_QUM_AGT_OPS_USR_ID, " & _
					"ROUND(AVG(OPS_QUM_SCORE),3) EVAL_SCORE " & _
					"FROM " & _
					"( " & _
						"SELECT " & _
						"OPS_QUM_AGT_OPS_USR_ID, " & _
						"OPS_QUM_SCORE, " & _
						"ROW_NUMBER() OVER (PARTITION BY OPS_QUM_AGT_OPS_USR_ID ORDER BY OPS_QUM_YEAR DESC, OPS_QUM_MONTH DESC) EVAL_NUM " & _
						"FROM OPS_QUALITY_MASTER " & _
						"JOIN OPS_FORM_MASTER " & _
						"ON OPS_QFM_ID = OPS_QUM_OPS_QFM_ID " & _
						"AND UPPER(OPS_QFM_NAME) LIKE '%MONTHLY EVALUATION' " & _
						"WHERE OPS_QUM_STATUS = 'COM' " & _
						"AND OPS_QUM_AGT_OPS_USR_ID IN " & _
						"( " & _
							"SELECT DISTINCT OPS_SCI_OPS_USR_ID " & _
							"FROM OPS_SCHEDULE_INFO " & _
							"JOIN RES_ROUTING " & _
							"ON OPS_SCI_OPS_USR_ID = RES_RTE_OPS_USR_ID " & _
							"AND RES_RTE_YEAR = TO_CHAR(CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE)-(6/24),'YYYY') " & _
							"AND RES_RTE_MONTH = TO_CHAR(CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE)-(6/24),'MM') " & _
							"WHERE TO_DATE(OPS_SCI_START) = TO_DATE(?,'MM/DD/YYYY') " & _
							"AND OPS_SCI_STATUS = 'SUB' " & _
							"AND OPS_SCI_OPS_USR_TYPE = 'RES' " & _
							"AND OPS_SCI_TYPE IN ('CDUN','CDPT') " & _
							"AND RES_RTE_RES_RTG_ID IN (4,5,13) " & _
							"AND CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE) < OPS_SCI_END " & _
						") " & _
					") " & _
					"WHERE EVAL_NUM <= 3 " & _
					"GROUP BY OPS_QUM_AGT_OPS_USR_ID " & _
				") " & _
				"ON OPS_USD_OPS_USR_ID = OPS_QUM_AGT_OPS_USR_ID " & _
				"LEFT JOIN " & _
				"( " & _
					"SELECT " & _
					"OPS_SCI_OPS_USR_ID, " & _
					"ROUND(SUM(24*(OPS_SCI_END-OPS_SCI_START)),1) UNPAID_HOURS " & _
					"FROM OPS_SCHEDULE_INFO		 " & _
					"WHERE OPS_SCI_STATUS = 'APP' " & _
					"AND REGEXP_LIKE(OPS_SCI_TYPE,'SLIP|HOLU|[^FM]UN$') " & _
					"AND TO_DATE(OPS_SCI_START) BETWEEN TO_DATE(?,'MM/DD/YYYY') - TO_CHAR(TO_DATE(?,'MM/DD/YYYY') ,'D') + 1 AND TO_DATE(?,'MM/DD/YYYY') - TO_CHAR(TO_DATE(?,'MM/DD/YYYY') ,'D') + 7 " & _
					"AND OPS_SCI_OPS_USR_ID IN " & _
					"( " & _
						"SELECT DISTINCT OPS_SCI_OPS_USR_ID " & _
						"FROM OPS_SCHEDULE_INFO " & _
						"JOIN RES_ROUTING " & _
						"ON OPS_SCI_OPS_USR_ID = RES_RTE_OPS_USR_ID " & _
						"AND RES_RTE_YEAR = TO_CHAR(CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE)-(6/24),'YYYY') " & _
						"AND RES_RTE_MONTH = TO_CHAR(CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE)-(6/24),'MM') " & _
						"WHERE TO_DATE(OPS_SCI_START) = TO_DATE(?,'MM/DD/YYYY') " & _
						"AND OPS_SCI_STATUS = 'SUB' " & _
						"AND OPS_SCI_OPS_USR_TYPE = 'RES' " & _
						"AND OPS_SCI_TYPE IN ('CDUN','CDPT') " & _
						"AND RES_RTE_RES_RTG_ID IN (4,5,13) " & _
						"AND CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE) < OPS_SCI_END " & _
					") " & _
					"GROUP BY OPS_SCI_OPS_USR_ID " & _
				") " & _
				"ON OPS_USD_OPS_USR_ID = OPS_SCI_OPS_USR_ID " & _
				"LEFT JOIN " & _
				"( " & _
					"SELECT " & _
					"OPS_PAR_PARENT_TYPE, " & _
					"REGEXP_SUBSTR(OPS_PAR_VALUE,'[^;]+',1,1) SCHEDULED_HOURS_MIN, " & _
					"REGEXP_SUBSTR(OPS_PAR_VALUE,'[^;]+',1,2) SCHEDULED_HOURS_MAX, " & _
					"REGEXP_SUBSTR(OPS_PAR_VALUE,'[^;]+',1,3) EVAL_MIN, " & _
					"REGEXP_SUBSTR(OPS_PAR_VALUE,'[^;]+',1,4) EVAL_MAX, " & _
					"REGEXP_SUBSTR(OPS_PAR_VALUE,'[^;]+',1,5) REDUCE_HOURS, " & _
					"OPS_PAR_EFF_DATE, " & _
					"OPS_PAR_DIS_DATE " & _
					"FROM OPS_PARAMETER " & _
					"WHERE OPS_PAR_CODE = 'REDUCE_LIMIT' " & _
					"AND OPS_PAR_PARENT_TYPE IN ('SPT','OSR') " & _
				") " & _
				"ON DECODE(OPS_USD_TEAM,'OSR','OSR','SPT') = OPS_PAR_PARENT_TYPE " & _
				"AND GREATEST(OPS_USD_SCH_HOURS,0.1) > SCHEDULED_HOURS_MIN " & _
				"AND GREATEST(OPS_USD_SCH_HOURS,0.1) <= SCHEDULED_HOURS_MAX " & _
				"AND LEAST(NVL(EVAL_SCORE,3),4.999) >= EVAL_MIN " & _
				"AND LEAST(NVL(EVAL_SCORE,3),4.999) < EVAL_MAX " & _
				"AND TO_DATE(?,'MM/DD/YYYY') BETWEEN OPS_PAR_EFF_DATE AND OPS_PAR_DIS_DATE " & _
			")CONDITIONS " & _
			"ON CD.OPS_USR_ID = CONDITIONS.OPS_USR_ID " & _
			"WHERE LEAST(CD_END,SCHEDULE_END) > GREATEST(CD_START,SCHEDULE_START,TO_DATE(CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE)) + ROUND(TO_CHAR(CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE),'SSSSS')/360)/240) " & _
		")CD " & _
		"JOIN OPS_USER_DETAIL " & _
		"ON CD.OPS_USR_ID = OPS_USD_OPS_USR_ID " & _
		"AND TO_DATE(CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE)) BETWEEN OPS_USD_EFF_DATE AND OPS_USD_DIS_DATE " & _
		"JOIN OPS_USER AGT " & _
		"ON CD.OPS_USR_ID = AGT.OPS_USR_ID " & _
		"JOIN OPS_USER SUP " & _
		"ON SUP.OPS_USR_ID = OPS_USD_SUPERVISOR " & _
		"LEFT JOIN RES_ROUTING " & _
		"ON RES_RTE_OPS_USR_ID = AGT.OPS_USR_ID " & _
		"AND RES_RTE_YEAR = TO_CHAR(CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE)-(6/24),'YYYY') " & _
		"AND RES_RTE_MONTH = TO_CHAR(CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE)-(6/24),'MM') " & _
		"LEFT JOIN " & _
		"( " & _
			"SELECT " & _
			"OPS_ASN_OPS_USR_ID, " & _
			"MAX(OPS_ASN_OPS_ASM_ID) OPS_ASN_OPS_ASM_ID " & _
			"FROM OPS_ASSIGNMENT " & _
			"WHERE OPS_ASN_OPS_ASM_ID IN (1,2,3,4,5,39,40,41,43,45,50) " & _
			"AND TO_DATE(?,'MM/DD/YYYY') BETWEEN OPS_ASN_EFF_DATE AND OPS_ASN_DIS_DATE " & _
			"GROUP BY OPS_ASN_OPS_USR_ID " & _
		") " & _
		"ON OPS_ASN_OPS_USR_ID = AGT.OPS_USR_ID " & _
		"LEFT JOIN " & _
		"( " & _
			"SELECT DISTINCT TO_NUMBER(TRIM(REGEXP_SUBSTR(RES_DLN_TEXT,'[^-]+',1,1))) NOTE_USR_ID " & _
			"FROM RES_DAILY_STATS_NOTES " & _
			"WHERE " & _
			"( " & _
				"( " & _
					"RES_DLN_DATE = TO_DATE(?,'MM/DD/YYYY') " & _
					"AND " & _
					"( " & _
						"TRIM(RES_DLN_TYPE) IN ('LATE','FLEX','SHFT','STRT','END','NFLX','OFLX','GAP','LMIN','OLAP','ABS','FWP','OTH','OUT','WFH','NA') " & _
						"OR " & _
						"( " & _
							"TRIM(RES_DLN_TYPE) = 'LWAV' " & _
							"AND DECODE(INSTR(RES_DLN_TEXT,'-'),0,NULL,TRIM(SUBSTR(RES_DLN_TEXT,INSTR(RES_DLN_TEXT,'-')+1))) IS NOT NULL " & _
						") " & _
					") " & _
				") " & _
				"OR " & _
				"( " & _
					"RES_DLN_DATE BETWEEN TO_DATE(?,'MM/DD/YYYY') - TO_CHAR(TO_DATE(?,'MM/DD/YYYY'),'D') + 1 AND TO_DATE(?,'MM/DD/YYYY') - TO_CHAR(TO_DATE(?,'MM/DD/YYYY'),'D') + 7 " & _
					"AND TRIM(RES_DLN_TYPE) = 'BWHC' " & _
				") " & _
			") " & _
		") " & _
		"ON CD.OPS_USR_ID = NOTE_USR_ID " & _
		"LEFT JOIN " & _
		"( " & _
			"SELECT DISTINCT TO_NUMBER(TRIM(REGEXP_SUBSTR(RES_DLN_TEXT,'[^-]+',1,1))) WAIVER_USR_ID " & _
			"FROM RES_DAILY_STATS_NOTES " & _
			"WHERE RES_DLN_DATE = TO_DATE(?,'MM/DD/YYYY') " & _
			"AND TRIM(RES_DLN_TYPE) = 'LWAV' " & _
		") " & _
		"ON CD.OPS_USR_ID = WAIVER_USR_ID " & _
		"WHERE CD_COUNT = 1 " & _
	")"


	SQLPendingOD = "SELECT DISTINCT " & _
	"OPS_SCI_OPS_USR_ID USE_AGENT, " & _
	"AGT.OPS_USR_NAME AGENT_NAME, " & _
	"SUP.OPS_USR_NAME SUPERVISOR_NAME, " & _
	"CASE " & _
		"WHEN OPS_USD_TYPE = 'POP' AND OPS_USD_TEAM = 'POC' THEN 'Product Ops' " & _
		"WHEN OPS_USD_TYPE = 'POP' AND OPS_USD_TEAM = 'DOC' THEN 'Documents' " & _
		"WHEN OPS_USD_TYPE = 'OSS' AND OPS_USD_TEAM = 'SKD' THEN 'Schedule Changes' " & _
		"WHEN OPS_USD_TYPE = 'OSS' AND OPS_USD_TEAM = 'PRD' THEN 'Product Support' " & _
		"WHEN OPS_USD_TYPE = 'OSS' AND OPS_USD_TEAM = 'AIR' THEN 'Air Support' " & _
		"WHEN OPS_USD_TYPE = 'OSS' AND OPS_USD_TEAM = 'LED' THEN 'OSS Leads' " & _
		"WHEN OPS_USD_TYPE = 'OPS' THEN 'OPS Desk' " & _
		"WHEN OPS_USD_TYPE = 'GRP' AND OPS_USD_JOB = 'SPC' THEN 'Group Product' " & _
		"WHEN OPS_USD_TYPE = 'GRP' AND OPS_USD_JOB = 'GSP' THEN 'Group Service' " & _
		"WHEN OPS_USD_TYPE = 'GRP' AND OPS_USD_JOB = 'GSM' THEN 'Group Sales' " & _
		"WHEN OPS_USD_TYPE = 'DOC' THEN 'Facilities' " & _
		"WHEN OPS_USD_TYPE = 'CRT' THEN 'Customer Relations' " & _
		"WHEN OPS_USD_TYPE = 'ACC' AND OPS_USD_TEAM = 'REC' THEN 'Account Receivable' " & _
		"WHEN OPS_USD_TYPE = 'ACC' AND OPS_USD_TEAM = 'PAY' THEN 'Account Payable' " & _
		"WHEN OPS_USD_TYPE = 'ACC' AND OPS_USD_TEAM = 'LDA' THEN 'Account Leads' " & _
	"END USE_WORKGROUP, " & _
	"DECODE(OPS_USD_CLASS,'RGFT','Reg Full-Time','RGPT','Reg Part-time','PT<30','PT Less Than 30','LEAVE','On Leave') USE_CLASS, " & _
	"DECODE(OPS_USD_LOCATION,'MOT','In-House','WFH','Work From Home','WFD','Work From Distance') USE_LOCATION, " & _
	"NVL2(NOTE_USR_ID,1,0) NOTE_BOOL, " & _
	"NVL2(WAIVER_USR_ID,1,0) WAIVER_BOOL, " & _
	"COUNT(*) OVER () AGENT_COUNT " & _
	"FROM OPS_SCHEDULE_INFO " & _
	"JOIN OPS_USER_DETAIL " & _
	"ON OPS_SCI_OPS_USR_ID = OPS_USD_OPS_USR_ID " & _
	"AND TO_DATE(?,'MM/DD/YYYY') BETWEEN OPS_USD_EFF_DATE AND OPS_USD_DIS_DATE " & _
	"JOIN OPS_USER AGT " & _
	"ON OPS_SCI_OPS_USR_ID = AGT.OPS_USR_ID " & _
	"JOIN OPS_USER SUP " & _
	"ON SUP.OPS_USR_ID = OPS_USD_SUPERVISOR " & _
	"LEFT JOIN " & _
	"( " & _
		"SELECT DISTINCT TO_NUMBER(TRIM(REGEXP_SUBSTR(RES_DLN_TEXT,'[^-]+',1,1))) NOTE_USR_ID " & _
		"FROM RES_DAILY_STATS_NOTES " & _
		"WHERE " & _
		"( " & _
			"( " & _
				"RES_DLN_DATE = TO_DATE(?,'MM/DD/YYYY') " & _
				"AND " & _
				"( " & _
					"TRIM(RES_DLN_TYPE) IN ('LATE','FLEX','SHFT','STRT','END','NFLX','OFLX','GAP','LMIN','OLAP','ABS','FWP','OTH','OUT','WFH','NA') " & _
					"OR " & _
					"( " & _
						"TRIM(RES_DLN_TYPE) = 'LWAV' " & _
						"AND DECODE(INSTR(RES_DLN_TEXT,'-'),0,NULL,TRIM(SUBSTR(RES_DLN_TEXT,INSTR(RES_DLN_TEXT,'-')+1))) IS NOT NULL " & _
					") " & _
				") " & _
			") " & _
			"OR " & _
			"( " & _
				"RES_DLN_DATE BETWEEN TO_DATE(?,'MM/DD/YYYY') - TO_CHAR(TO_DATE(?,'MM/DD/YYYY'),'D') + 1 AND TO_DATE(?,'MM/DD/YYYY') - TO_CHAR(TO_DATE(?,'MM/DD/YYYY'),'D') + 7 " & _
				"AND TRIM(RES_DLN_TYPE) = 'BWHC' " & _
			") " & _
		") " & _
	") " & _
	"ON OPS_SCI_OPS_USR_ID = NOTE_USR_ID " & _
	"LEFT JOIN " & _
	"( " & _
		"SELECT DISTINCT TO_NUMBER(TRIM(REGEXP_SUBSTR(RES_DLN_TEXT,'[^-]+',1,1))) WAIVER_USR_ID " & _
		"FROM RES_DAILY_STATS_NOTES " & _
		"WHERE RES_DLN_DATE = TO_DATE(?,'MM/DD/YYYY') " & _
		"AND TRIM(RES_DLN_TYPE) = 'LWAV' " & _
	") " & _
	"ON OPS_SCI_OPS_USR_ID = WAIVER_USR_ID " & _
	"WHERE OPS_SCI_STATUS = 'SUB' " & _
	"AND OPS_USD_TYPE = ? " & _
	"AND NOT " & _
	"( " & _
		"OPS_USD_TYPE = 'GRP' " & _
		"AND OPS_USD_TEAM = 'SPT' " & _
	") " & _
	"AND TO_DATE(OPS_SCI_START) = TO_DATE(?,'MM/DD/YYYY') " & _
	"AND OPS_SCI_END > CAST(SYSTIMESTAMP AT TIME ZONE 'US/CENTRAL' AS DATE) " & _
	"ORDER BY AGT.OPS_USR_NAME"
%>