<%
	PulsePreTradeSQL = "SELECT " & _
	"TO_DATE(OPS_SCI_START) SCI_DATE, " & _
	"TO_CHAR(OPS_SCI_START,'HH24:MI') SCI_START, " & _
	"TO_CHAR(OPS_SCI_END,'HH24:MI') SCI_END, " & _
	"OPS_SCI_TYPE, " & _
	"OPS_SCI_STATUS, " & _
	"OPS_SCI_NOTES, " & _
	"CASE " & _
		"WHEN OPS_SCI_TYPE IN ('PICK','BASE','HOLW','ADDT','EXTD') THEN 'PHONE' " & _
		"WHEN OPS_SCI_TYPE IN ('MEET','PRES','PROJ','TRAN','FAMP','WFHU','MLTU','OTRG','NEWH') THEN 'TRAIN' " & _
		"WHEN OPS_SCI_TYPE IN ('SRPT','SRUN') THEN 'SRED' " & _
		"WHEN OPS_SCI_TYPE IN ('LNCH','LNFL') THEN 'LUNCH' " & _
		"WHEN REGEXP_LIKE(OPS_SCI_TYPE,'^VAC|UN$|PT$|PP$|HOLU|HOLR|SLIP|RESH|RCHG|ROUT|JURY|BRVT') THEN 'VACA' " & _
	"END SCHEDULE_CLASS, " & _
	"CASE " & _
		"WHEN (OPS_SCI_TYPE NOT IN ('HOLR','HOLU') OR RES_BUE_ID IS NULL) AND OPS_SCI_END <> NVL(LEAD(OPS_SCI_START) OVER (ORDER BY TO_DATE(OPS_SCI_START), DECODE(OPS_SCI_STATUS,'APP',1,'SUB',2,'OPT',3), CASE WHEN RES_BUE_ID IS NOT NULL AND OPS_SCI_TYPE IN ('HOLR','HOLU') THEN 1 ELSE 2 END, OPS_SCI_START, OPS_SCI_END, DECODE(REGEXP_INSTR(OPS_SCI_TYPE,'UN$|PP$|PT$'),0,OPS_SCI_TYPE,'AA'||OPS_SCI_TYPE)),OPS_SCI_END) THEN 1 " & _
		"WHEN OPS_SCI_TYPE IN ('HOLR','HOLU') AND RES_BUE_ID IS NOT NULL AND LEAD(OPS_SCI_TYPE) OVER (ORDER BY TO_DATE(OPS_SCI_START), DECODE(OPS_SCI_STATUS,'APP',1,'SUB',2,'OPT',3), CASE WHEN RES_BUE_ID IS NOT NULL AND OPS_SCI_TYPE IN ('HOLR','HOLU') THEN 1 ELSE 2 END, OPS_SCI_START, OPS_SCI_END, DECODE(REGEXP_INSTR(OPS_SCI_TYPE,'UN$|PP$|PT$'),0,OPS_SCI_TYPE,'AA'||OPS_SCI_TYPE)) NOT IN ('HOLR','HOLU') THEN 1 " & _
		"ELSE 0 " & _
	"END GAP_FLAG " & _
	"FROM " & _
	"( " & _
		"SELECT " & _
		"OPS_SCI_START, " & _
		"OPS_SCI_END, " & _
		"OPS_SCI_TYPE, " & _
		"OPS_SCI_STATUS, " & _
		"OPS_SCI_NOTES " & _
		"FROM OPS_SCHEDULE_INFO " & _
		"WHERE OPS_SCI_STATUS = 'APP' " & _
		"AND TO_DATE(OPS_SCI_START) = TO_DATE(?,'MM/DD/YYYY') " & _
		"AND OPS_SCI_OPS_USR_ID = ? " & _
	") " & _
	"LEFT JOIN RES_BUDGET_EXCEPTION " & _
	"ON TO_DATE(OPS_SCI_START) = RES_BUE_DATE " & _
	"AND RES_BUE_TYPE = 'NOR' " & _
	"ORDER BY CASE WHEN RES_BUE_ID IS NOT NULL AND OPS_SCI_TYPE IN ('HOLR','HOLU') THEN 1 ELSE 2 END, OPS_SCI_START, OPS_SCI_END, DECODE(REGEXP_INSTR(OPS_SCI_TYPE,'UN$|PP$|PT$'),0,OPS_SCI_TYPE,'AA'||OPS_SCI_TYPE)"
		
	PulsePostTradeOutSQL = "SELECT " & _
	"OPS_SCI_ID, " & _
	"TO_DATE(OPS_SCI_START) SCI_DATE, " & _
	"TO_CHAR(OPS_SCI_START,'HH24:MI') SCI_START, " & _
	"CASE " & _
		"WHEN TO_CHAR(OPS_SCI_START,'HH24:MI') <> TO_CHAR(OPS_SCI_END,'HH24:MI') AND TO_CHAR(OPS_SCI_END,'HH24:MI') = '00:00' THEN '24:00' " & _
		"ELSE TO_CHAR(OPS_SCI_END,'HH24:MI') " & _
	"END SCI_END, " & _
	"OPS_SCI_TYPE, " & _
	"CASE WHEN OPS_SCI_STATUS = 'SUB' THEN 'DEL' WHEN OPS_SCI_TYPE IN ('HOLR','HOLU') AND RES_BUE_ID IS NOT NULL THEN 'APP' ELSE 'DEL' END OPS_SCI_STATUS, " & _
	"OPS_SCI_NOTES, " & _
	"CASE " & _
		"WHEN OPS_SCI_TYPE IN ('PICK','BASE','HOLW','ADDT','EXTD') THEN 'PHONE' " & _
		"WHEN OPS_SCI_TYPE IN ('MEET','PRES','PROJ','TRAN','FAMP','WFHU','MLTU','OTRG','NEWH') THEN 'TRAIN' " & _
		"WHEN OPS_SCI_TYPE IN ('SRPT','SRUN') THEN 'SRED' " & _
		"WHEN OPS_SCI_TYPE IN ('LNCH','LNFL') THEN 'LUNCH' " & _
		"WHEN REGEXP_LIKE(OPS_SCI_TYPE,'^VAC|UN$|PT$|PP$|HOLU|HOLR|SLIP|RESH|RCHG|ROUT|JURY|BRVT') THEN 'VACA' " & _
	"END SCHEDULE_CLASS, " & _
	"CASE " & _
		"WHEN (OPS_SCI_TYPE NOT IN ('HOLR','HOLU') OR RES_BUE_ID IS NULL) AND OPS_SCI_END <> NVL(LEAD(OPS_SCI_START) OVER (ORDER BY TO_DATE(OPS_SCI_START), DECODE(OPS_SCI_STATUS,'APP',1,'SUB',2,'OPT',3), CASE WHEN RES_BUE_ID IS NOT NULL AND OPS_SCI_TYPE IN ('HOLR','HOLU') THEN 1 ELSE 2 END, OPS_SCI_START, OPS_SCI_END, DECODE(REGEXP_INSTR(OPS_SCI_TYPE,'UN$|PP$|PT$'),0,OPS_SCI_TYPE,'AA'||OPS_SCI_TYPE)),OPS_SCI_END) THEN 1 " & _
		"WHEN OPS_SCI_TYPE IN ('HOLR','HOLU') AND RES_BUE_ID IS NOT NULL AND LEAD(OPS_SCI_TYPE) OVER (ORDER BY TO_DATE(OPS_SCI_START), DECODE(OPS_SCI_STATUS,'APP',1,'SUB',2,'OPT',3), CASE WHEN RES_BUE_ID IS NOT NULL AND OPS_SCI_TYPE IN ('HOLR','HOLU') THEN 1 ELSE 2 END, OPS_SCI_START, OPS_SCI_END, DECODE(REGEXP_INSTR(OPS_SCI_TYPE,'UN$|PP$|PT$'),0,OPS_SCI_TYPE,'AA'||OPS_SCI_TYPE)) NOT IN ('HOLR','HOLU') THEN 1 " & _
	"ELSE 0 " & _
	"END GAP_FLAG " & _
	"FROM " & _
	"( " & _
		"SELECT " & _
		"OPS_SCI_ID, " & _
		"OPS_SCI_START, " & _
		"OPS_SCI_END, " & _
		"OPS_SCI_TYPE, " & _
		"OPS_SCI_STATUS, " & _
		"OPS_SCI_NOTES " & _
		"FROM OPS_SCHEDULE_INFO " & _
		"WHERE OPS_SCI_STATUS IN ('APP','SUB') " & _
		"AND TO_DATE(OPS_SCI_START) = TO_DATE(?,'MM/DD/YYYY') " & _
		"AND OPS_SCI_OPS_USR_ID = ? " & _
	") " & _
	"LEFT JOIN RES_BUDGET_EXCEPTION " & _
	"ON TO_DATE(OPS_SCI_START) = RES_BUE_DATE " & _
	"AND RES_BUE_TYPE = 'NOR' " & _
	"ORDER BY CASE WHEN RES_BUE_ID IS NOT NULL AND OPS_SCI_TYPE IN ('HOLR','HOLU') THEN 1 ELSE 2 END, OPS_SCI_START, OPS_SCI_END, DECODE(REGEXP_INSTR(OPS_SCI_TYPE,'UN$|PP$|PT$'),0,OPS_SCI_TYPE,'AA'||OPS_SCI_TYPE)"
	
	PulsePostTradeInSQL = "SELECT " & _
	"OPS_SCI_ID, " & _
	"TO_DATE(OPS_SCI_START) SCI_DATE, " & _
	"TO_CHAR(OPS_SCI_START,'HH24:MI') SCI_START, " & _
	"CASE " & _
		"WHEN TO_CHAR(OPS_SCI_START,'HH24:MI') <> TO_CHAR(OPS_SCI_END,'HH24:MI') AND TO_CHAR(OPS_SCI_END,'HH24:MI') = '00:00' THEN '24:00' " & _
		"ELSE TO_CHAR(OPS_SCI_END,'HH24:MI') " & _
	"END SCI_END, " & _
	"OPS_SCI_TYPE, " & _
	"OPS_SCI_STATUS, " & _
	"OPS_SCI_NOTES, " & _
	"CASE " & _
		"WHEN OPS_SCI_TYPE IN ('PICK','BASE','HOLW','ADDT','EXTD') THEN 'PHONE' " & _
		"WHEN OPS_SCI_TYPE IN ('MEET','PRES','PROJ','TRAN','FAMP','WFHU','MLTU','OTRG','NEWH') THEN 'TRAIN' " & _
		"WHEN OPS_SCI_TYPE IN ('SRPT','SRUN') THEN 'SRED' " & _
		"WHEN OPS_SCI_TYPE IN ('LNCH','LNFL') THEN 'LUNCH' " & _
		"WHEN REGEXP_LIKE(OPS_SCI_TYPE,'^VAC|UN$|PT$|PP$|HOLU|HOLR|SLIP|RESH|RCHG|ROUT|JURY|BRVT') THEN 'VACA' " & _
	"END SCHEDULE_CLASS, " & _
	"CASE " & _
		"WHEN (OPS_SCI_TYPE NOT IN ('HOLR','HOLU') OR RES_BUE_ID IS NULL) AND OPS_SCI_END <> NVL(LEAD(OPS_SCI_START) OVER (ORDER BY TO_DATE(OPS_SCI_START), DECODE(OPS_SCI_STATUS,'APP',1,'SUB',2,'OPT',3), CASE WHEN RES_BUE_ID IS NOT NULL AND OPS_SCI_TYPE IN ('HOLR','HOLU') THEN 1 ELSE 2 END, OPS_SCI_START, OPS_SCI_END, DECODE(REGEXP_INSTR(OPS_SCI_TYPE,'UN$|PP$|PT$'),0,OPS_SCI_TYPE,'AA'||OPS_SCI_TYPE)),OPS_SCI_END) THEN 1 " & _
		"WHEN OPS_SCI_TYPE IN ('HOLR','HOLU') AND RES_BUE_ID IS NOT NULL AND LEAD(OPS_SCI_TYPE) OVER (ORDER BY TO_DATE(OPS_SCI_START), DECODE(OPS_SCI_STATUS,'APP',1,'SUB',2,'OPT',3), CASE WHEN RES_BUE_ID IS NOT NULL AND OPS_SCI_TYPE IN ('HOLR','HOLU') THEN 1 ELSE 2 END, OPS_SCI_START, OPS_SCI_END, DECODE(REGEXP_INSTR(OPS_SCI_TYPE,'UN$|PP$|PT$'),0,OPS_SCI_TYPE,'AA'||OPS_SCI_TYPE)) NOT IN ('HOLR','HOLU') THEN 1 " & _
		"ELSE 0 " & _
	"END GAP_FLAG, " & _
	"TRADE_FLAG " & _
	"FROM " & _
	"( " & _
		"SELECT " & _
		"OPS_SCI_ID, " & _
		"OPS_SCI_START, " & _
		"OPS_SCI_END, " & _
		"OPS_SCI_TYPE, " & _
		"DECODE(OPS_SCI_STATUS,'SUB','DEL',DECODE(OPS_SCI_TYPE,'HOLR','APP','HOLU','APP',DECODE(?,1,'DEL','APP'))) OPS_SCI_STATUS, " & _
		"OPS_SCI_NOTES, " & _
		"0 TRADE_FLAG " & _
		"FROM OPS_SCHEDULE_INFO " & _
		"WHERE OPS_SCI_STATUS IN ('APP','SUB') " & _
		"AND TO_DATE(OPS_SCI_START) = TO_DATE(?,'MM/DD/YYYY') " & _
		"AND OPS_SCI_OPS_USR_ID = ? " & _
		"UNION ALL " & _
		"SELECT " & _
		"-1, " & _
		"OPS_SCI_START, " & _
		"OPS_SCI_END, " & _
		"DECODE(OPS_SCI_TYPE,'LNCH','LNCH','LNFL','LNFL','BASE') OPS_SCI_TYPE, " & _
		"'APP', " & _
		"'Shift Trade with ' || ? || ' for ' || ? OPS_SCI_NOTES, " & _
		"1 " & _
		"FROM OPS_SCHEDULE_INFO " & _
		"WHERE OPS_SCI_STATUS = 'APP' " & _
		"AND TO_DATE(OPS_SCI_START) = TO_DATE(?,'MM/DD/YYYY') " & _
		"AND OPS_SCI_OPS_USR_ID = ? " & _
		"AND OPS_SCI_TYPE NOT IN ('HOLR','HOLU') " & _
	") " & _
	"LEFT JOIN RES_BUDGET_EXCEPTION " & _
	"ON TO_DATE(OPS_SCI_START) = RES_BUE_DATE " & _
	"AND RES_BUE_TYPE = 'NOR' " & _
	"ORDER BY SCI_DATE, DECODE(OPS_SCI_STATUS,'APP',1,'SUB',2,'OPT',3), CASE WHEN RES_BUE_ID IS NOT NULL AND OPS_SCI_TYPE IN ('HOLR','HOLU') THEN 1 ELSE 2 END, OPS_SCI_START, OPS_SCI_END, DECODE(REGEXP_INSTR(OPS_SCI_TYPE,'UN$|PP$|PT$'),0,OPS_SCI_TYPE,'AA'||OPS_SCI_TYPE)"
%>